# Configuration for probot-stale - https://github.com/probot/stale
# This file is used on Blender's GitHub mirror to automatically close any pull request
# and invite contributors to join the official development platform on blender.org

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 1

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 1

# Label to use when marking as stale
staleLabel: stale

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue has been automatically closed, because this repository is only
  used as a mirror of git.blender.org. Blender development happens on
  developer.blender.org.

  To get started contributing code, please read:
  https://wiki.blender.org/wiki/Process/Contributing_Code
