sudo: required

language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      
cache:
  timeout: 5000
  directories:
    - $HOME

compiler:
  - gcc

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - nvidia-cuda-dev
          - libcuda1-384
          - build-essential
          - gcc-7-multilib
          - gcc-7
          - g++-7
          - cmake
          - doxygen
          - libpython3.6-dev
    install: travis_wait 60 mvn install
    install: 
      - mkdir ../lib && cd ../lib/ && RUN svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64
      - cd ../ && ls & cd bforartists
      - make -f GNUmakefile 
    before_deploy:
      - export RELEASE_FILE=$(ls *.deb)
      - echo "Deploying $RELEASE_FILE to GitHub"
    deploy:
      provider: releases
      api_key:
        secure: "ERlWoOkrphep39WP0GCsrJuIT2PxoQq4bxUrHZMLXq7Swlf7paDlXPW8C2yS2S1DOpRmZrD3jwIp8lu1OhVYoke8rGURXdRvKyNKpHUfYYDZZmY81sAhYQPCXW3AblurbgqpzJkwJADDA108KYJ6RQ/iOYVdmxaJ1hz/LYGBVbl5Us2i7iGY1JlC3SMNXDt2AH3aLHlOltywNaOcus9aSATGyQVcbzToBh7AhrzvlDNVV1huMwOFEVu9PFnxS8J7KtBVK/tQ3vJEvNkcusCMN5p5Ut8C423MQj/26GBkKN0FJ8wOAuXvi32F1/6F2vFx7Vguzqs/+YQMRdeP5ReLgdBNDJNFuoR0M5hlcXNGNJKY+O5rPJJMaT0S78t5vYD5Bt+9cyNIPnbai6dOlqahAvMEzrdoTJrhK+E0aAgKqybOLObJeqmPCDXsgBo+su3ZHk5nBRH1RQtg6ToYVl2wmZJd/BkwLnLYzzT5sHD4gddHxOFa5uSqUqR9RQeL2olL21lCj8wJ4k43jb9zAqZ7qtgSDCFVpIgnvOO2fVIhfKb6OteaEkD8B4D3mLdlq9N73v9nFASviqM7ry5GOaLHPqSPya9Lv3rArHUzHso2sf2KtJB7Z/uYYiCxgFU5/YN+ajngrovzqvU43HsF9ShjcMmwrxadHqR45/6U+qq82HQ="
      file_glob: true
      file: ${RELEASE_FILE}
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
    env:
      - MATRIX_EVAL="gcc && CXX=g++ && NPROC=$(nproc)"
  - os: osx
    osx_image: xcode8
    addons:
      apt:
        packages:
          - svn
    install: svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/darwin ../lib/darwin --trust-server-cert --non-interactive  
    before_deploy:
      - export RELEASE_FILE=$(ls *.dmg)
      - echo "Deploying $RELEASE_FILE to GitHub"
    deploy:
      provider: releases
      api_key:
        secure: "ERlWoOkrphep39WP0GCsrJuIT2PxoQq4bxUrHZMLXq7Swlf7paDlXPW8C2yS2S1DOpRmZrD3jwIp8lu1OhVYoke8rGURXdRvKyNKpHUfYYDZZmY81sAhYQPCXW3AblurbgqpzJkwJADDA108KYJ6RQ/iOYVdmxaJ1hz/LYGBVbl5Us2i7iGY1JlC3SMNXDt2AH3aLHlOltywNaOcus9aSATGyQVcbzToBh7AhrzvlDNVV1huMwOFEVu9PFnxS8J7KtBVK/tQ3vJEvNkcusCMN5p5Ut8C423MQj/26GBkKN0FJ8wOAuXvi32F1/6F2vFx7Vguzqs/+YQMRdeP5ReLgdBNDJNFuoR0M5hlcXNGNJKY+O5rPJJMaT0S78t5vYD5Bt+9cyNIPnbai6dOlqahAvMEzrdoTJrhK+E0aAgKqybOLObJeqmPCDXsgBo+su3ZHk5nBRH1RQtg6ToYVl2wmZJd/BkwLnLYzzT5sHD4gddHxOFa5uSqUqR9RQeL2olL21lCj8wJ4k43jb9zAqZ7qtgSDCFVpIgnvOO2fVIhfKb6OteaEkD8B4D3mLdlq9N73v9nFASviqM7ry5GOaLHPqSPya9Lv3rArHUzHso2sf2KtJB7Z/uYYiCxgFU5/YN+ajngrovzqvU43HsF9ShjcMmwrxadHqR45/6U+qq82HQ="
      file_glob: true
      file: ${RELEASE_FILE}
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
    env:
      - MATRIX_EVAL="NPROC=$(sysctl -n hw.physicalcpu)"

script:
  - mkdir build
  - cd build
  - cmake -DCPACK_BINARY_DEB:BOOL=True .. && make install && make package
