sudo: required

language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

compiler:
  - gcc

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - build-essential
          - gcc-6-multilib
          - gcc-6
          - g++-6
          - cmake
          - doxygen
    env:
      - MATRIX_EVAL="gcc-6 && CXX=g++-6 && NPROC=$(nproc)"
  - os: osx
    osx_image: xcode8
    env:
      - MATRIX_EVAL="NPROC=$(sysctl -n hw.physicalcpu)"
      
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# Before compile
install:
  - ./build_files/build_environment/install_deps.sh --build-all --no-confirm

script:
  - mkdir build
  - cd build
  - cmake .. && make
