sudo: required

language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

compiler:
  - gcc

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc-4.9
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - build-essential
          - gcc-4.8-multilib
          - gcc-4.9
          - g++-4.9
          - cmake
          - doxygen
          - python3
          - python3-dev
          - python3-pip
    env:
      - MATRIX_EVAL="gcc-4.9 && CXX=g++-4.9 && NPROC=$(nproc)"
  - os: osx
    osx_image: xcode8
    env:
      - MATRIX_EVAL="NPROC=$(sysctl -n hw.physicalcpu)"
      
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# Before compile
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - pip3 install numpy
  - ./build_files/build_environment/install_deps.sh --build-all --no-confirm

script:
  - mkdir build
  - cd build
  - cmake .. && make
