schema_version = "1.0.0"
id = "export_camera_animation"
name = "Export Camera Animation"
version = "0.1.0"
tagline = "Export Cameras & Markers (.py)"
maintainer = "Community"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/io_anim_camera"
copyright = ["2024 Campbell Barton"]
