schema_version = "1.0.0"
id = "viewport_pie_menus"
name = "3D Viewport Pie Menus - Bforartists Version"
version = "1.3.0"
tagline = "Extra Pie Menus" #BFA - a bit more explicit
maintainer = "Community"
type = "add-on"
tags = ["User Interface"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/space_view3d_pie_menus"
copyright = ["2024 meta-androcto"]
