/* SPDX-FileCopyrightText: 2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/** \file
 * \ingroup nodes
 */

/* intentionally no include guard */

/* Keep aligned args for readability. */
/* clang-format off */

/* Empty definitions for undefined macros to avoid warnings */
#ifndef DefNode
#define DefNode(Category, ID, DefFunc, EnumName, StructName, UIName, UIDesc)
#endif

/* WARNING! If you edit those strings, please do the same in relevant nodes files (under blender/nodes/...)! */

/*       Tree type       Node ID                  RNA def function         Struct name       UI Name              UI Description */
DefNode(Node,            NODE_FRAME,               def_frame,           Frame,             "Frame",              "Add a frame\nA frame allows to collect nodes together.\nUseful for organization when the re-usability of a node group is not required")
DefNode(Node,            NODE_GROUP_INPUT,         def_group_input,     GroupInput,        "Group Input",        "Add a Group Input node\nExpose connected data from inside a node group as inputs to its interface")
DefNode(Node,            NODE_GROUP_OUTPUT,        def_group_output,    GroupOutput,       "Group Output",       "Add a Group Output node\nOutput data from inside of a node group")
DefNode(Node,            NODE_GROUP,               def_group,           Group,             "Group",              "Create a node group from the selected nodes")
DefNode(Node,            NODE_REROUTE,             def_reroute,         Reroute,           "Reroute",            "Add a reroute point\nReroute points can be used to reroute connections for organization\nSupports one input and multiple outputs")

DefNode(ShaderNode,     SH_NODE_BRIGHTCONTRAST,  0, BrightContrast,   "Brightness/Contrast","Add a Bright/Contrast Shader node\nControl the brightness and contrast of the input color")
DefNode(ShaderNode,     SH_NODE_CAMERA,          0,         CameraData,       "Camera Data",       "Add a Camera Data Shader node\nGet information about the position of the object relative to the camera")
DefNode(ShaderNode,     SH_NODE_CLAMP,           def_clamp,          Clamp,            "Clamp",             "Add a Clamp Shader node\nClamps a value between a minimum and a maximum")
DefNode(ShaderNode,     SH_NODE_COMBRGB_LEGACY,  0,        CombineRGB,       "Combine RGB",       "Add a Combine RGB Shader node\nCombine the single RGB channels into a single image (Deprecated)")
DefNode(ShaderNode,     SH_NODE_CURVE_RGB,       def_rgb_curve,      RGBCurve,         "RGB Curves",        "Add a RGB Curves Shader node\nApply color corrections for each color channel and levels adjustments in the compositing context")
DefNode(ShaderNode,     SH_NODE_CURVE_VEC,       def_vector_curve,      VectorCurve,      "Vector Curves",     "Add a Vector Curves node\nMap input vector components with curves")
DefNode(ShaderNode,     SH_NODE_GAMMA,           0,          Gamma,            "Gamma",             "Add a Gamma Shader node\nApply a gamma correction")
DefNode(ShaderNode,     SH_NODE_HUE_SAT,         0,        HueSaturation,    "Hue/Saturation/Value","Add a Hue/Saturation/Value Shader node\nColor transformation in the HSV color space")
DefNode(ShaderNode,     SH_NODE_INVERT,          0,         Invert,           "Invert Color",      "Add an Invert Color Shader node\nInverts the colors in the input image, producing a negative")
DefNode(ShaderNode,     SH_NODE_MAP_RANGE,       def_map_range,      MapRange,         "Map Range",         "Add a Map Range Shader node\nRemaps a value from a source range to a target range")
DefNode(ShaderNode,     SH_NODE_MAPPING,         def_sh_mapping,        Mapping,          "Mapping",           "Add a Mapping Shader node\nTransform the input vector by applying translation, rotation, and scale")
DefNode(ShaderNode,     SH_NODE_MATH,            def_math,           Math,             "Math",              "Add a Math Shader node\nPerforms math operations")
DefNode(ShaderNode,     SH_NODE_MIX_RGB_LEGACY,  def_mix_rgb,        MixRGB,           "MixRGB",            "Add a Mix RGB Shader node\nMixes images by working on the individual and corresponding pixels of the two input images")
DefNode(ShaderNode,     SH_NODE_NORMAL,          0,         Normal,           "Normal",            "Add a Normal Shader node\nGenerate a normal vector and a dot product")
DefNode(ShaderNode,     SH_NODE_RGB,             0,            RGB,              "RGB",               "Add a RGB Shader node\nSet a color with a color picker")
DefNode(ShaderNode,     SH_NODE_RGBTOBW,         0,        RGBToBW,          "RGB to BW",         "Add a RGB to BW Shader node\nConverts an RGB color image to a gray-scale image based at its luminance")
DefNode(ShaderNode,     SH_NODE_SEPRGB_LEGACY,   0,         SeparateRGB,      "Separate RGB",      "Add a Separate RGB Shader node\nSeparates the single RGB channels from a single image (Deprecated)")
DefNode(ShaderNode,     SH_NODE_SHADERTORGB,     0,    ShaderToRGB,      "Shader to RGB",     "Add a Shader to RGB Shader node\nConvert PBR rendering effect (such as light and shadow) to RGBA color. Typically used for non-photorealistic rendering to apply additional effects on the output of BSDFs.\nNote: only supported for Eevee\n Warning, this may break the PBR workflow")
DefNode(ShaderNode,     SH_NODE_SQUEEZE,         0,        Squeeze,          "Squeeze Value",     "Add a Squeeze Value Shader node\nScale down high values of the camera data node")
DefNode(ShaderNode,     SH_NODE_VALTORGB,        def_colorramp,       ValToRGB,         "Color Ramp",        "Add a Color Ramp Shader node\nMap values to colors with the use of a gradient")
DefNode(ShaderNode,     SH_NODE_VALUE,           0,          Value,            "Value",             "Add a Value Shader node\nUsed to Input numerical values to other nodes in the tree")
DefNode(ShaderNode,     SH_NODE_VECTOR_MATH,     def_vector_math,      VectorMath,       "Vector Math",       "Add a Vector Math Shader node\nPerforms a selected math operation on the input vectors")

DefNode(ShaderNode,     SH_NODE_ADD_SHADER,          0,          AddShader,         "Add Shader",         "Add a Add Shader Shader node\nAdds two Shaders together"       )
DefNode(ShaderNode,     SH_NODE_AMBIENT_OCCLUSION,   def_sh_ambient_occlusion,  AmbientOcclusion,  "Ambient Occlusion",  "Add a Ambient Occlusion Shader node\nAmbient Occlusion is a technique to self shadow the geometry of objects"       )
DefNode(ShaderNode,     SH_NODE_ATTRIBUTE,           def_sh_attribute,           Attribute,         "Attribute",          "Add a Attribute Shader node\nAllows you to retrieve attributes attached to an object or mesh"       )
DefNode(ShaderNode,     SH_NODE_BACKGROUND,          0,          Background,        "Background",         "Add a Background Shader node\nAdd background light emission"       )
DefNode(ShaderNode,     SH_NODE_BEVEL,               def_sh_bevel,               Bevel,             "Bevel",              "Add a Bevel Shader node\nRender rounded corners to capture specular highlights"       )
DefNode(ShaderNode,     SH_NODE_BLACKBODY,           0,           Blackbody,         "Blackbody",          "Add a Blackbody Shader node\nConverts a blackbody temperature to RGB value"       )
DefNode(ShaderNode,     SH_NODE_BSDF_DIFFUSE,        0,        BsdfDiffuse,       "Diffuse BSDF",       "Add a Diffuse BSDF Shader node\nLambertian and Oren-Nayar diffuse reflection"       )
DefNode(ShaderNode,     SH_NODE_BSDF_GLASS,          def_glass,          BsdfGlass,         "Glass BSDF",         "Add a Glass BSDF Shader node\nA glass shader"       )
DefNode(ShaderNode,     SH_NODE_BSDF_GLOSSY,         def_glossy,         BsdfAnisotropic,        "Glossy BSDF",        "Add a Glossy BSDF Shader node\nnAdds an anisotropic reflection with micro facet distribution"       )
DefNode(ShaderNode,     SH_NODE_BSDF_HAIR,           def_hair,           BsdfHair,          "Hair BSDF",          "Add a Hair BSDF Shader node\nAdd shading for Hair"       )
DefNode(ShaderNode,     SH_NODE_BSDF_HAIR_PRINCIPLED,   def_hair_principled,  BsdfHairPrincipled,   "Principled Hair BSDF",  "Add a Principled Hair BSDF Shader node\nShading for Hair and Fur")
DefNode(ShaderNode,     SH_NODE_BSDF_METALLIC,       def_metallic,    BsdfMetallic,      "Metallic BSDF",      "Add a Metallic BSDF Shader node\nMetallic reflection with microfacet distribution, and metallic fresnel")
DefNode(ShaderNode,     SH_NODE_BSDF_PRINCIPLED,     def_principled,     BsdfPrincipled,    "Principled BSDF",    "Add a Principled BSDF Shader node\nPhysically-based, easy-to-use combined shader node for rendering surface materials.\n Based on the Disney principled model also known as the PBR Shader"       )
DefNode(ShaderNode,     SH_NODE_BSDF_RAY_PORTAL,    0,    BsdfRayPortal,    "Ray Portal BSDF",   "Add a Ray Portal BSDF Shader node\nContinue tracing from an arbitrary new position and in a new direction")
DefNode(ShaderNode,     SH_NODE_BSDF_REFRACTION,     def_refraction,     BsdfRefraction,    "Refraction BSDF",    "Add a Refraction BSDF Shader node\nAdds glossy refraction with sharp or micro facet distribution"       )
DefNode(ShaderNode,     SH_NODE_BSDF_SHEEN,         def_sheen,         BsdfSheen,        "Sheen BSDF",        "Add a Sheen/Velvet BSDF Shader node\nAdds sheen/velvet reflection to materials, such as cloth\nTypically mixed with other shaders (such as a Diffuse Shader) and is not particularly useful on its own"       )
DefNode(ShaderNode,     SH_NODE_BSDF_TOON,           def_toon,           BsdfToon,          "Toon BSDF",          "Add a Toon BSDF Shader node\nCreate Diffuse and Glossy materials with cartoon light effects"       )
DefNode(ShaderNode,     SH_NODE_BSDF_TRANSLUCENT,    0,    BsdfTranslucent,   "Translucent BSDF",   "Add a Translucent BSDF Shader node\nAdds Lambertian diffuse transmission"       )
DefNode(ShaderNode,     SH_NODE_BSDF_TRANSPARENT,    0,    BsdfTransparent,   "Transparent BSDF",   "Add a Transparent BSDF Shader node\nAdds transparency without refraction"       )
DefNode(ShaderNode,     SH_NODE_BUMP,                def_sh_bump,                Bump,              "Bump",               "Add a Bump Shader node\nGenerates a perturbed normal from a height texture, for bump mapping"       )
DefNode(ShaderNode,     SH_NODE_COMBHSV_LEGACY,      0,             CombineHSV,        "Combine HSV",        "Add a Combine HSV Shader node\nCombine the single HSV channels into a single image"       )
DefNode(ShaderNode,     SH_NODE_COMBINE_COLOR,       def_sh_combsep_color,       CombineColor,      "Combine Color",      "Add a Combine Color Shader node\nCombines single colors to a rgb, hsv or hsl color value"       )
DefNode(ShaderNode,     SH_NODE_COMBXYZ,             0,             CombineXYZ,        "Combine XYZ",        "Add a Combine XYZ Shader node\nCombine the single RGB channels into a single image by values between 0 and 1"       )
DefNode(ShaderNode,     SH_NODE_CURVE_FLOAT,         def_float_curve,         FloatCurve,        "Float Curve",        "Add a Curve Float Shader node\nMaps an input float to a curve and outputs a float value"       )
DefNode(ShaderNode,     SH_NODE_DISPLACEMENT,        def_sh_displacement,        Displacement,      "Displacement",       "Add a Displacement Shader node\nDisplace the surface along all the surface normal"       )
DefNode(ShaderNode,     SH_NODE_EEVEE_SPECULAR,      0,      EeveeSpecular,     "Specular BSDF",      "Add a Specular BSDF Shader node\nCombines multiple shader layers in a single node"       )
DefNode(ShaderNode,     SH_NODE_EMISSION,            0,            Emission,          "Emission",           "Add a Emission Shader node\nThe Emission node emits light"       )
DefNode(ShaderNode,     SH_NODE_FRESNEL,             0,             Fresnel,           "Fresnel",            "Add a Fresnel Shader node\nAdds Fresnel effect. The more a face goes towards 180 degrees, the more it is reflecting"       )
DefNode(ShaderNode,     SH_NODE_HAIR_INFO,           0,           HairInfo,          "Curves Info",         "Add a Curves Info Shader node\nGives access to Hair information"       )
DefNode(ShaderNode,     SH_NODE_HOLDOUT,             0,             Holdout,           "Holdout",            "Add a Holdout Shader node\nCreate a “hole” in the image with zero alpha transparency"       )
DefNode(ShaderNode,     SH_NODE_LAYER_WEIGHT,        0,        LayerWeight,       "Layer Weight",       "Add a Layer Weight Shader node\nOutputs a weight. Typically used for layering shaders with the Mix Shader node"       )
DefNode(ShaderNode,     SH_NODE_LIGHT_FALLOFF,       0,       LightFalloff,      "Light Falloff",      "Add a Light Falloff Shader node\nAllows you to manipulate how light intensity decreases over distance"       )
DefNode(ShaderNode,     SH_NODE_LIGHT_PATH,          0,          LightPath,         "Light Path",         "Add a Light Path Shader node\nRetreives for which kind of incoming ray the shader is being executed"       )
DefNode(ShaderNode,     SH_NODE_MIX_SHADER,          0,          MixShader,         "Mix Shader",         "Add a Mix Shader Shader node\nMix two shaders together by a factor"       )
DefNode(ShaderNode,     SH_NODE_MIX,                 def_sh_mix,                 Mix,               "Mix",                "Add a Mix Shader node\nMixes values by a factor")
DefNode(ShaderNode,     SH_NODE_NEW_GEOMETRY,        0,        NewGeometry,       "Geometry",           "Add a Geometry Shader node\nGives geometric information about the current shading point"       )
DefNode(ShaderNode,     SH_NODE_NORMAL_MAP,          def_sh_normal_map,          NormalMap,         "Normal Map",         "Add a Normal Map Shader node\nGenerates a perturbed normal from an RGB normal map image"       )
DefNode(ShaderNode,     SH_NODE_OBJECT_INFO,         0,         ObjectInfo,        "Object Info",        "Add a Object Info Shader node\nRetreives information about the object instance"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_AOV,          def_sh_output_aov,          OutputAOV,         "AOV Output",         "Add a AOV Output Shader node\nProvides custom render passes for arbitrary shader node components\nNote that the AOV Node is NOT compatible with Cycles in the realtime compositor!"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_LIGHT,        def_sh_output,        OutputLight,       "Light Output",       "Add a Light Output Shader node\nOutputs light information to a light object"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_LINESTYLE,    def_sh_output_linestyle,    OutputLineStyle,   "Line Style Output",  "Add a Line Style Output Shader node\nA Line Style shader"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_MATERIAL,     def_sh_output,     OutputMaterial,    "Material Output",    "Add a Material Output Shader node\nOutput surface material information to a surface object"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_WORLD,        def_sh_output,        OutputWorld,       "World Output",       "Add a World Output Shader node\nOutputs light and color information to the scene’s World"       )
DefNode(ShaderNode,     SH_NODE_PARTICLE_INFO,       0,       ParticleInfo,      "Particle Info",      "Add a Particle Info Shader node\nGet access to the data of the particle that spawned the object instance"       )
DefNode(ShaderNode,     SH_NODE_POINT_INFO,          0,          PointInfo,         "Point Info",         "Add a Point Info Shader node\nRetreive info from a point cloud"       )
DefNode(ShaderNode,     SH_NODE_SCRIPT,              def_sh_script,              Script,            "Script",             "Add a Script Shader node\nIn this node you can load OSL shaders.\nNote: OSL shaders are not supported on all GPU backends"       )
DefNode(ShaderNode,     SH_NODE_SEPARATE_COLOR,      def_sh_combsep_color,      SeparateColor,     "Separate Color",     "Add a Separate Color Shader node\nSeparates the values of a rgb, hsv or hsl color into its single values"       )
DefNode(ShaderNode,     SH_NODE_SEPHSV_LEGACY,       0,              SeparateHSV,       "Separate HSV",       "Add a Separate HSV Shader node\nSeparates the single HSV channels from a single image"       )
DefNode(ShaderNode,     SH_NODE_SEPXYZ,              0,              SeparateXYZ,       "Separate XYZ",       "Add a Separate XYZ Shader node\nSeparates the single RGB channels from a single image by values between 0 and 1"       )
DefNode(ShaderNode,     SH_NODE_SUBSURFACE_SCATTERING,  def_sh_subsurface, SubsurfaceScattering, "Subsurface Scattering", "Add a Subsurface Scattering Shader node\nSimple subsurface multiple scattering, for skin, wax, etc")
DefNode(ShaderNode,     SH_NODE_TANGENT,             def_sh_tangent,             Tangent,           "Tangent",            "Add a Tangent Shader node\nGenerates a tangent direction for the Anisotropic BSDF"       )
DefNode(ShaderNode,     SH_NODE_TEX_BRICK,           def_sh_tex_brick,           TexBrick,          "Brick Texture",      "Add a Brick Texture Shader node\nAdds a procedural brick texture"       )
DefNode(ShaderNode,     SH_NODE_TEX_CHECKER,         def_sh_tex_checker,         TexChecker,        "Checker Texture",    "Add a Checker Texture Shader node\nAdds a procedural checkerboard texture"       )
DefNode(ShaderNode,     SH_NODE_TEX_COORD,           def_sh_tex_coord,           TexCoord,          "Texture Coordinate", "Add a Texture Coordinate Shader node\nDefine some texture coordinate types"       )
DefNode(ShaderNode,     SH_NODE_TEX_ENVIRONMENT,     def_sh_tex_environment,     TexEnvironment,    "Environment Texture", "Add a Environment Texture Shader node\nLoad an environment texture to light your scene"      )
DefNode(ShaderNode,     SH_NODE_TEX_GABOR,           def_sh_tex_gabor,           TexGabor,          "Gabor Texture",      "Add a Gabor Texture Node\nGenerate Gabor texture noise")
DefNode(ShaderNode,     SH_NODE_TEX_GRADIENT,        def_sh_tex_gradient,        TexGradient,       "Gradient Texture",   "Add a Gradient Texture Shader node\nGenerates interpolated color and intensity values based on the input vector"       )
DefNode(ShaderNode,     SH_NODE_TEX_IES,             def_sh_tex_ies,             TexIES,            "IES Texture",        "Add a IES Texture Shader node\nMatch real world lights based on IES files"       )
DefNode(ShaderNode,     SH_NODE_TEX_IMAGE,           def_sh_tex_image,           TexImage,          "Image Texture",      "Add an Image Texture Shader node\nAdd an image file as a texture"       )
DefNode(ShaderNode,     SH_NODE_TEX_MAGIC,           def_sh_tex_magic,           TexMagic,          "Magic Texture",      "Add a Magic Texture Shader node\nAdds a procedural psychedelic color texture"       )
DefNode(ShaderNode,     SH_NODE_TEX_NOISE,           def_sh_tex_noise,           TexNoise,          "Noise Texture",      "Add a Noise Texture Shader node\nEvaluates a fractal Perlin noise at the input texture coordinates"       )
DefNode(ShaderNode,     SH_NODE_TEX_POINTDENSITY,    def_sh_tex_pointdensity,    TexPointDensity,   "Point Density",      "Add a Point Density Shader node\nAdds volumetric points for each particle or vertex of another object"       )
DefNode(ShaderNode,     SH_NODE_TEX_SKY,             def_sh_tex_sky,             TexSky,            "Sky Texture",        "Add a Sky Texture Shader node\nAdds a procedural Sky texture"       )
DefNode(ShaderNode,     SH_NODE_TEX_VORONOI,         def_sh_tex_voronoi,         TexVoronoi,        "Voronoi Texture",    "Add a Voronoi Texture Shader node\nEvaluates a Worley Noise at the input texture coordinates"       )
DefNode(ShaderNode,     SH_NODE_TEX_WAVE,            def_sh_tex_wave,            TexWave,           "Wave Texture",       "Add a Wave Texture Shader node\nAdds procedural bands or rings with noise distortion"       )
DefNode(ShaderNode,     SH_NODE_TEX_WHITE_NOISE,     def_sh_tex_white_noise,     TexWhiteNoise,     "White Noise Texture",        "Add a White Noise Texture Shader node\nAdds white noise"       )
DefNode(ShaderNode,     SH_NODE_UVALONGSTROKE,       def_sh_uvalongstroke,       UVAlongStroke,     "UV Along Stroke",    "Add a UV Along Stroke Shader node\nMaps textures along the stroke length"       )
DefNode(ShaderNode,     SH_NODE_UVMAP,               def_sh_uvmap,               UVMap,             "UV Map",             "Add a UV Map Shader node\nRetrieve specific UV maps"       )
DefNode(ShaderNode,     SH_NODE_VECT_TRANSFORM,      def_sh_vect_transform,      VectorTransform,   "Vector Transform",   "Add a Vector Transform Shader node\nConvert a vector, point, or normal between world and camera and object coordinate space"       )
DefNode(ShaderNode,     SH_NODE_VECTOR_DISPLACEMENT, def_sh_vector_displacement, VectorDisplacement, "Vector Displacement", "Add a Vector Displacement Shader node\nDisplace the surface along arbitrary directions"  )
DefNode(ShaderNode,     SH_NODE_VECTOR_ROTATE,       def_sh_vector_rotate,       VectorRotate,      "Vector Rotate",      "Add a Vector Rotate Shader node\nRotate a vector around a center point"       )
DefNode(ShaderNode,     SH_NODE_VERTEX_COLOR,        def_sh_vertex_color,        VertexColor,       "Color Attribute",    "Add a Color Attribute Shader node\nProvides vertex colors as well as their alpha value"       )
DefNode(ShaderNode,     SH_NODE_VOLUME_ABSORPTION,   0,   VolumeAbsorption,  "Volume Absorption",  "Add a Volume Absorption Shader node\nAllows light to be absorbed as it passes through the volume"       )
DefNode(ShaderNode,     SH_NODE_VOLUME_INFO,         0,         VolumeInfo,        "Volume Info",        "Add a Volume Info Shader node\nRetreives information about Smoke Domains"       )
DefNode(ShaderNode,     SH_NODE_VOLUME_PRINCIPLED,   0,   VolumePrincipled,  "Principled Volume",  "Add a Principled Volume Shader node\nAll volume shading components in a single node"       )
DefNode(ShaderNode,     SH_NODE_VOLUME_SCATTER,      def_scatter,      VolumeScatter,     "Volume Scatter",     "Add a Volume Scatter Shader node\nAllows light to be scattered as it passes through the volume"       )
DefNode(ShaderNode,     SH_NODE_WAVELENGTH,          0,          Wavelength,        "Wavelength",         "Add a Wavelength Shader node\nConverts a wavelength value to an RGB value"       )
DefNode(ShaderNode,     SH_NODE_WIREFRAME,           def_sh_tex_wireframe,           Wireframe,         "Wireframe",          "Add a Wireframe Shader node\nRetreive and render the wireframe, triangulated"       )

/* NOTE: #OutputFile node has special RNA setup function called in `rna_nodetree.cc`. */
DefNode(CompositorNode,  CMP_NODE_ALPHAOVER,       def_cmp_alpha_over,       AlphaOver,         "Alpha Over",         "Add a Alpha Over Compositor node\nLayer images with an alpha channel on top of one another"              )
DefNode(CompositorNode,  CMP_NODE_BLUR,            def_cmp_blur,            Blur,              "Blur",               "Add a Blur Compositor node\nBlur an image"              )
DefNode(CompositorNode,  CMP_NODE_COMPOSITE,       def_cmp_composite,       Composite,         "Composite",          "Add a Composite Compositor node\nComposite output to the renderer"              )
DefNode(CompositorNode,  CMP_NODE_CURVE_RGB,       def_rgb_curve,       CurveRGB,          "RGB Curves",         "Add a RGB Curves Compositor node\nAllows color corrections for each color channel and levels adjustments"              )
DefNode(CompositorNode,  CMP_NODE_CURVE_VEC,       def_vector_curve,       CurveVec,          "Vector Curves",      "Add a Vector Curves Compositor node\nMaps an input vector components to a curve"              )
DefNode(CompositorNode,  CMP_NODE_FILTER,          def_cmp_filter,          Filter,            "Filter",             "Add a Filter Compositor node\nProvides various common image enhancement filters"              )
DefNode(CompositorNode,  CMP_NODE_HUE_SAT,         0,         HueSat,            "Hue/Saturation/Value", "Add a Hue/Saturation/Value Compositor node\nApply a color transformation in the HSV color space"            )
DefNode(CompositorNode,  CMP_NODE_IMAGE,           def_cmp_image,           Image,             "Image",              "Add an Image Compositor node\nImage input"              )
DefNode(CompositorNode,  CMP_NODE_MAP_RANGE,       def_cmp_map_range,       MapRange,          "Map Range",          "Add a Map Range Compositor node\nRemaps a value from a source range to a target range"              )
DefNode(CompositorNode,  CMP_NODE_MAP_VALUE,       def_cmp_map_value,       MapValue,          "Map Value",          "Add a Map Value Compositor node\nScale, offset and clamp values"              )
DefNode(CompositorNode,  CMP_NODE_MIX_RGB,         def_mix_rgb,         MixRGB,            "Mix",                "Add a Mix Compositor node\nMixes images by working on the individual and corresponding pixels of the two input images"              )
DefNode(CompositorNode,  CMP_NODE_NORMAL,          0,          Normal,            "Normal",             "Add a Normal Compositor node\nGenerates a normal vector and a dot product"              )
DefNode(CompositorNode,  CMP_NODE_R_LAYERS,        def_cmp_render_layers,        RLayers,           "Render Layers",      "Add a Render Layers Compositor node\nInputs the available render layers"              )
DefNode(CompositorNode,  CMP_NODE_RGB,             0,             RGB,               "RGB",                "Add a RGB Compositor node\nSets a color"              )
DefNode(CompositorNode,  CMP_NODE_RGBTOBW,         0,         RGBToBW,           "RGB to BW",          "Add a RGB to BW Compositor node\nConverts an RGB color image to a gray-scale image based at its luminance"              )
DefNode(CompositorNode,  CMP_NODE_SEPHSVA_LEGACY,  0,         SepHSVA,           "Separate HSVA",      "Add a Separate HSVA Compositor node\nSeparates the single RGB channels from a single image"              )
DefNode(CompositorNode,  CMP_NODE_SEPRGBA_LEGACY,  0,         SepRGBA,           "Separate RGBA",      "Add a Separate RGBA Compositor node\nSeparates the RGBA values from a single image"              )
DefNode(CompositorNode,  CMP_NODE_SETALPHA,        def_cmp_set_alpha,        SetAlpha,          "Set Alpha",          "Add a Set Alpha Compositor node\nAdds an alpha channel to an image"              )
DefNode(CompositorNode,  CMP_NODE_TIME,            def_time,            Time,              "Time Curve",           "Add a Time Curve Compositor node\ngenerates a factor value that changes according to the curve as time progresses through the Timeline"              )
DefNode(CompositorNode,  CMP_NODE_VALTORGB,        def_colorramp,        ValToRGB,          "Color Ramp",          "Add a Color Ramp Compositor node\nMap color values by gradient"              )
DefNode(CompositorNode,  CMP_NODE_VALUE,           0,           Value,             "Value",              "Add a Value Compositor node\nInput numerical values to other nodes"              )
DefNode(CompositorNode,  CMP_NODE_VECBLUR,         def_cmp_vector_blur,         VecBlur,           "Vector Blur",        "Add a Vector Blur Compositor node\nUses the vector speed render pass to blur the image pixels in 2D"              )
DefNode(CompositorNode,  CMP_NODE_VIEWER,          def_cmp_viewer,          Viewer,            "Viewer",             "Add a Viewer Compositor node\nDisplays the output as a backdrop in the viewport or in the Image editor"              )
DefNode(CompositorNode, CMP_NODE_ANTIALIASING,    def_cmp_antialiasing,    AntiAliasing,      "Anti-Aliasing",      "Add a Anti-Aliasing Compositor node\nAnti-alias an image"              )
DefNode(CompositorNode, CMP_NODE_BILATERALBLUR,   def_cmp_bilateral_blur,   Bilateralblur,     "Bilateral Blur",     "Add a Bilateral Blur Compositor node\nPerforms a high-quality adaptive blur on the source image"              )
DefNode(CompositorNode, CMP_NODE_BOKEHBLUR,       def_cmp_bokehblur,       BokehBlur,         "Bokeh Blur",         "Add a Bokeh Blur Compositor node\nGenerates a bokeh type blur"              )
DefNode(CompositorNode, CMP_NODE_BOKEHIMAGE,      def_cmp_bokehimage,      BokehImage,        "Bokeh Image",        "Add a Bokeh Image Compositor node\nGenerates a special input image for use with the Bokeh Blur filter node"              )
DefNode(CompositorNode, CMP_NODE_BRIGHTCONTRAST,  def_cmp_brightcontrast,  BrightContrast,    "Brightness/Contrast",    "Add a Brightness/Contrast Compositor node\nAdjust the brightness and contrast"              )
DefNode(CompositorNode, CMP_NODE_CHANNEL_MATTE,   def_cmp_channel_matte,   ChannelMatte,      "Channel Key",        "Add a Channel Key Compositor node\nDetermines background objects from foreground objects by the difference in the selected channel’s levels"              )
DefNode(CompositorNode, CMP_NODE_CHROMA_MATTE,    def_cmp_chroma_matte,    ChromaMatte,       "Chroma Key",         "Add a Chroma Key Compositor node\nDetermines if a pixel is a foreground or background (and thereby should be transparent) based on its chroma values"              )
DefNode(CompositorNode, CMP_NODE_COLOR_MATTE,     def_cmp_color_matte,     ColorMatte,        "Color Key",          "Add a Color Key Compositor node\nCreates a matte based on a specified color of the input image"              )
DefNode(CompositorNode, CMP_NODE_COLOR_SPILL,     def_cmp_color_spill,     ColorSpill,        "Color Spill",        "Add a Color Spill Compositor node\nReduces one of the RGB channels so that it is not greater than any of the others"              )
DefNode(CompositorNode, CMP_NODE_COLORBALANCE,    def_cmp_colorbalance,    ColorBalance,      "Color Balance",      "Add a Color Balance Compositor node\nAdjust the color and values of an image"              )
DefNode(CompositorNode, CMP_NODE_COLORCORRECTION, def_cmp_colorcorrection, ColorCorrection,   "Color Correction",   "Add a Color Correction Compositor node\nAdjust the color of an image"              )
DefNode(CompositorNode, CMP_NODE_COMBHSVA_LEGACY, 0,        CombHSVA,          "Combine HSVA",       "Add a Combine HSVA Compositor node\nCombine the single HSV channels into a single image"              )
DefNode(CompositorNode, CMP_NODE_COMBINE_COLOR,   def_cmp_combsep_color,   CombineColor,      "Combine Color",      "Add a Separate Color Compositor node\nSeparates the values of a rgb, hsv or hsl color into its single values"              )
DefNode(CompositorNode, CMP_NODE_COMBINE_XYZ,     0,     CombineXYZ,        "Combine XYZ",        "Add a Combine XYZ Compositor Node\nCombine the single RGB channels into a single image by values between 0 and 1")
DefNode(CompositorNode, CMP_NODE_COMBRGBA_LEGACY, 0,        CombRGBA,          "Combine RGBA",       "Add a Combine RGBA Compositor node\nCombine the single RGB channels into a single image"              )
DefNode(CompositorNode, CMP_NODE_COMBYCCA_LEGACY, def_cmp_ycc,        CombYCCA,          "Combine YCbCrA",     "Add a Combine YCbCrA Compositor node\nConverts an YCbCrA image to RGBA color space and unions the channels"              )
DefNode(CompositorNode, CMP_NODE_COMBYUVA_LEGACY, 0,        CombYUVA,          "Combine YUVA",       "Add a Combine YUVA Compositor node\nConverts an YUVA image to RGBA color space"              )
DefNode(CompositorNode, CMP_NODE_CONVERT_COLOR_SPACE, def_cmp_convert_color_space,  ConvertColorSpace,  "Convert Colorspace", "Add a Color Space Node\nConvert the color space from one color space to another"       )
DefNode(CompositorNode, CMP_NODE_CORNERPIN,       0,       CornerPin,         "Corner Pin",         "Add a Corner Pin Compositor node\nUses explicit corner values for a plane warp transformation"              )
DefNode(CompositorNode, CMP_NODE_CROP,            def_cmp_crop,            Crop,              "Crop",               "Add a Crop Compositor node\nCrops an image to a selected region"              )
DefNode(CompositorNode, CMP_NODE_CRYPTOMATTE_LEGACY,  def_cmp_cryptomatte_legacy,  Cryptomatte,  "Cryptomatte (Legacy)",  "Add a Cryptomatte (Legacy) Compositor node\ncreate mattes for compositing. Deprecated method"           )
DefNode(CompositorNode, CMP_NODE_CRYPTOMATTE,     def_cmp_cryptomatte,  CryptomatteV2,     "Cryptomatte",        "Add a Cryptomatte Compositor node\nCreate mattes for compositing"              )
DefNode(CompositorNode, CMP_NODE_DBLUR,           def_cmp_dblur,           DBlur,             "Directional Blur",   "Add a Directional Blur Compositor node\nBlurs an image in a specified direction and magnitude"              )
DefNode(CompositorNode, CMP_NODE_DEFOCUS,         def_cmp_defocus,         Defocus,           "Defocus",            "Add a Defocus Compositor node\nEmulates depth of field (DOF)"              )
DefNode(CompositorNode, CMP_NODE_DENOISE,         def_cmp_denoise,         Denoise,           "Denoise",            "Add a Denoise Compositor node\nDenoises the image"              )
DefNode(CompositorNode, CMP_NODE_DESPECKLE,       def_cmp_despeckle,       Despeckle,         "Despeckle",          "Add a Despeckle Compositor node\nSmooth areas of an image in which noise is noticeable"              )
DefNode(CompositorNode, CMP_NODE_DIFF_MATTE,      def_cmp_diff_matte,      DiffMatte,         "Difference Key",     "Add a Difference Key Compositor node\nProduces a matte that isolates foreground content by comparing it with a reference background image"              )
DefNode(CompositorNode, CMP_NODE_DILATEERODE,     def_cmp_dilate_erode,     DilateErode,       "Dilate/Erode",       "Add a Dilate/Erode Compositor node\nProvides a morphology filter to dilate or erode the image"              )
DefNode(CompositorNode, CMP_NODE_DISPLACE,        0,        Displace,          "Displace",           "Add a Displace Compositor node\nDisplaces the pixel position based on an input vector"              )
DefNode(CompositorNode, CMP_NODE_DIST_MATTE,      def_cmp_distance_matte,  DistanceMatte,     "Distance Key",       "Add a Distance Key Compositor node\nDetermines a pixel’s alpha value"              )
DefNode(CompositorNode, CMP_NODE_DOUBLEEDGEMASK,  def_cmp_double_edge_mask,  DoubleEdgeMask,   "Double Edge Mask",   "Add a Double Edge Mask Compositor node\nCreates a gradient between two masks"              )
DefNode(CompositorNode, CMP_NODE_EXPOSURE,        0,        Exposure,          "Exposure",           "Add a Exposure Compositor node\nMake areas of an image brighter or dimmer"              )
DefNode(CompositorNode, CMP_NODE_FLIP,            def_cmp_flip,            Flip,              "Flip",               "Add a Flip Compositor node\nFlips an image at defined axis"              )
DefNode(CompositorNode, CMP_NODE_GAMMA,           0,           Gamma,             "Gamma",              "Add a Gamma Compositor node\nApply a gamma correction"              )
DefNode(CompositorNode, CMP_NODE_GLARE,           def_cmp_glare,           Glare,             "Glare",              "Add a Glare Compositor node\nAdds lens flares, fog, glows around exposed parts of an image"              )
DefNode(CompositorNode, CMP_NODE_HUECORRECT,      def_cmp_huecorrect,      HueCorrect,        "Hue Correct",        "Add a Hue Correct Compositor node\nAdjust the Hue, Saturation, and Value of an image with an input curve"              )
DefNode(CompositorNode, CMP_NODE_ID_MASK,         def_cmp_id_mask,         IDMask,            "ID Mask",            "Add a ID Mask Compositor node\nAccess an alpha mask per object or per material"              )
DefNode(CompositorNode, CMP_NODE_INPAINT,         def_cmp_inpaint,         Inpaint,           "Inpaint",            "Add a Inpaint Compositor node\nExtend borders of an image into transparent or masked regions"              )
DefNode(CompositorNode, CMP_NODE_INVERT,          def_cmp_invert,          Invert,            "Invert Color",             "Add an Invert Color Compositor node\nInverts the colors in the input image, producing a negative"              )
DefNode(CompositorNode, CMP_NODE_KEYING,          def_cmp_keying,          Keying,            "Keying",             "Add a Keying Compositor node\nPerforms chroma keying to remove the backdrop and despill to correct color cast from the backdrop"              )
DefNode(CompositorNode, CMP_NODE_KEYINGSCREEN,    def_cmp_keyingscreen,    KeyingScreen,      "Keying Screen",      "Add a Keying Screen Compositor node\nCreates plates for use as a color reference for keying nodes"              )
DefNode(CompositorNode, CMP_NODE_KUWAHARA,        def_cmp_kuwahara,       Kuwahara,         "Kuwahara",          "Add a Kuwahara Compositor node\nKuwahara is a stylize filter")
DefNode(CompositorNode, CMP_NODE_LENSDIST,        def_cmp_lensdist,        Lensdist,          "Lens Distortion",    "Add a Lens Distortion Compositor node\nSimulate distortions from real camera lenses"              )
DefNode(CompositorNode, CMP_NODE_LUMA_MATTE,      def_cmp_luma_matte,      LumaMatte,         "Luminance Key",      "Add a Luminance Key Compositor node\nDetermines background objects from foreground objects by the difference in the brightness level"              )
DefNode(CompositorNode, CMP_NODE_MAP_UV,          def_cmp_map_uv,          MapUV,             "Map UV",             "Add a Map UV Compositor node\nAllows to re-texture objects after they have been rendered"              )
DefNode(CompositorNode, CMP_NODE_MASK_BOX,        def_cmp_boxmask,         BoxMask,           "Box Mask",           "Add a Box Mask Compositor node\nCreates an image suitable for use as a simple matte"              )
DefNode(CompositorNode, CMP_NODE_MASK_ELLIPSE,    def_cmp_ellipsemask,     EllipseMask,       "Ellipse Mask",       "Add a Ellipse Mask Compositor node\ncreates an image suitable for use as a simple matte or vignette mask"              )
DefNode(CompositorNode, CMP_NODE_MASK,            def_cmp_mask,            Mask,              "Mask",               "Add a Mask Compositor node\nThe Mask node can be used to select a Mask data"              )
DefNode(CompositorNode, CMP_NODE_MATH,            def_math,            Math,              "Math",               "Add a Math Compositor node\nPerforms math operations"              )
DefNode(CompositorNode, CMP_NODE_MOVIECLIP,       def_cmp_movieclip,       MovieClip,         "Movie Clip",         "Add a Movie Clip Compositor node\nTakes values from footage cameras and trackings, and links them to the output"              )
DefNode(CompositorNode, CMP_NODE_MOVIEDISTORTION, def_cmp_moviedistortion, MovieDistortion,   "Movie Distortion",   "Add a Movie Distortion Compositor node\nAdds distortion to render or removes distortion from movies to make them fit together "              )
DefNode(CompositorNode, CMP_NODE_NORMALIZE,       0,       Normalize,         "Normalize",          "Add a Normalize Compositor node\nFind the minimum and maximum values of a single channel in the range of 0 and 1. "              )
DefNode(CompositorNode, CMP_NODE_OUTPUT_FILE,     0,     OutputFile,        "File Output",        "Add a File Output Compositor node\nWrites out an image as part of a frame set sequence"              )
DefNode(CompositorNode, CMP_NODE_PIXELATE,        def_cmp_pixelate,        Pixelate,          "Pixelate",           "Add a Pixelate Compositor node\nAdd this node in front of a Scale node to get a pixelated (non-smoothed) image"              )
DefNode(CompositorNode, CMP_NODE_PLANETRACKDEFORM,def_cmp_planetrackdeform, PlaneTrackDeform, "Plane Track Deform",  "Add a Plan track Deform node\nReplace flat planes in footage by another image, detected by plane tracks from motion tracking")
DefNode(CompositorNode, CMP_NODE_POSTERIZE,       0,       Posterize,         "Posterize",          "Add a Posterize Node\nPosterize reduces the number of colors"              )
DefNode(CompositorNode, CMP_NODE_PREMULKEY,       def_cmp_premul_key,       PremulKey,         "Alpha Convert",      "Add a Alpha Convert Compositor node\nConverts the alpha channel interpretation of an image from pre-multiplied to straight or vice versa"              )
DefNode(CompositorNode, CMP_NODE_ROTATE,          def_cmp_rotate,          Rotate,            "Rotate",             "Add a Rotate Compositor node\nRotate a texture"              )
DefNode(CompositorNode, CMP_NODE_SCALE,           def_cmp_scale,           Scale,             "Scale",              "Add a Scale Compositor node\nScale a texture"              )
DefNode(CompositorNode, CMP_NODE_SCENE_TIME,      0,      SceneTime,         "Scene Time",         "Add a Scene Time Node\nOutputs the current scene time in seconds or in frames"              )
DefNode(CompositorNode, CMP_NODE_SEPARATE_COLOR,  def_cmp_combsep_color,  SeparateColor,     "Separate Color",     "Add a Combine Color Compositor node\nCombines single colors to a rgb, hsv or hsl color value"               )
DefNode(CompositorNode, CMP_NODE_SEPARATE_XYZ,    0,    SeparateXYZ,       "Separate XYZ",       "Add a Separate XYZ Compositor Node\nSeparates the single RGB channels from a single image by values between 0 and 1")
DefNode(CompositorNode, CMP_NODE_SEPYCCA_LEGACY,  def_cmp_ycc,         SepYCCA,           "Separate YCbCrA",    "Add a Separate YCbCrA Compositor node\nConverts an RGBA image to YCbCrA color space, and splits it to single output"              )
DefNode(CompositorNode, CMP_NODE_SEPYUVA_LEGACY,  0,         SepYUVA,           "Separate YUVA",      "Add a Separate YUVA Compositor node\nConverts an RGBA image to YUVA color space"              )
DefNode(CompositorNode, CMP_NODE_SPLIT,           def_cmp_split,           Split,             "Split",              "Add a Split Compositor node\ndisplays two images side-by-side as backdrop, or as a Viewer Node output"              )
DefNode(CompositorNode, CMP_NODE_STABILIZE2D,     def_cmp_stabilize2d,     Stabilize,         "Stabilize 2D",       "Add a Stabilize 2D Compositor node\nStabilizes the footage according to the settings set in Movie Clip Editor"              )
DefNode(CompositorNode, CMP_NODE_SUNBEAMS,        def_cmp_sunbeams,        SunBeams,          "Sun Beams",          "Add a Sun Beams Compositor node\nCreates 2D sun beams"              )
DefNode(CompositorNode, CMP_NODE_SWITCH_VIEW,     def_cmp_switch_view,      SwitchView,        "Switch View",        "Add a Switch View Compositor node\nCombines the views (left and right) into a single Stereo 3D output"              )
DefNode(CompositorNode, CMP_NODE_SWITCH,          def_cmp_switch,          Switch,            "Switch",             "Add a Switch Compositor node\nSwitch between two images"              )
DefNode(CompositorNode, CMP_NODE_TEXTURE,         def_texture,         Texture,           "Texture",            "Add a Texture Compositor node\nAllows you to use 3D textures in the Compositor"              )
DefNode(CompositorNode, CMP_NODE_TONEMAP,         def_cmp_tonemap,         Tonemap,           "Tonemap",            "Add a Tonemap Compositor node\nAllows Tonemapping"              )
DefNode(CompositorNode, CMP_NODE_TRACKPOS,        def_cmp_trackpos,        TrackPos,          "Track Position",     "Add a Track Position Compositor node\nreturn information about a tracking marker to the Compositor\nYou need a tracking project"              )
DefNode(CompositorNode, CMP_NODE_TRANSFORM,       dev_cmd_transform,       Transform,         "Transform",          "Add a Transform Compositor node\nMove, rotate or scale an image"              )
DefNode(CompositorNode, CMP_NODE_TRANSLATE,       def_cmp_translate,       Translate,         "Translate",          "Add a Translate Compositor node\nMove an image"              )
DefNode(CompositorNode, CMP_NODE_VIEW_LEVELS,     def_cmp_levels,          Levels,            "Levels",             "Add a Levels Compositor node\nReads the inputs color channels and outputs analytical values"              )
DefNode(CompositorNode, CMP_NODE_ZCOMBINE,        def_cmp_zcombine,        Zcombine,          "Z Combine",          "Add a Z Combine Compositor node\nCombines two images based on their Z-depth maps"              )

DefNode(TextureNode,     TEX_NODE_AT,              0,              At,                "At",                 "Add a At Texture node\nReturns the color of a texture at the specified coordinates"              )
DefNode(TextureNode,     TEX_NODE_BRICKS,          def_tex_bricks,          Bricks,            "Bricks",             "Add a Brick Texture node\nAdds a procedural brick texture"              )
DefNode(TextureNode,     TEX_NODE_CHECKER,         0,         Checker,           "Checker",            "Add a Checker Texture node\nAdds a procedural checkerboard texture"              )
DefNode(TextureNode,     TEX_NODE_COMBINE_COLOR,   def_tex_combsep_color,   CombineColor,      "Combine Color",      "Add a Combine Color Texture node\nCombines single colors to a rgb, hsv or hsl color value"              )
DefNode(TextureNode,     TEX_NODE_COMPOSE_LEGACY,  0,         Compose,           "Combine RGBA",       "Add a Combine RGBA Texture node\nCombine the single RGB channels into a single imag"              )
DefNode(TextureNode,     TEX_NODE_COORD,           0,           Coordinates,       "Coordinates",        "Add a Coordinates Texture node\nOutputs the geometry local coordinates, relative to its bounding box as RGB colors"              )
DefNode(TextureNode,     TEX_NODE_CURVE_RGB,       def_rgb_curve,       CurveRGB,          "RGB Curves",         "Add a RGB Curves Texture node\nAllows color corrections for each color channel and levels adjustments"              )
DefNode(TextureNode,     TEX_NODE_CURVE_TIME,      def_time,      CurveTime,         "Curve Time",         "Add a Curve Time Texture node\nAdjust the changes over time by curves"              )
DefNode(TextureNode,     TEX_NODE_DECOMPOSE_LEGACY, 0,       Decompose,         "Separate RGBA",      "Add a Separate RGBA Texture node\nSeparates the single RGBA channels from a single image"              )
DefNode(TextureNode,     TEX_NODE_DISTANCE,        0,        Distance,          "Distance",           "Add a Distance Texture node\nComputes the distance between two 3D coordinates"              )
DefNode(TextureNode,     TEX_NODE_HUE_SAT,         0,         HueSaturation,     "Hue/Saturation/Value",	  "Add a Hue/Saturation/Value Texture node\nColor transformation in the HSV color space"              )
DefNode(TextureNode,     TEX_NODE_IMAGE,           def_tex_image,           Image,             "Image",              "Add an Image Texture node\nAdd an image file as a texture"              )
DefNode(TextureNode,     TEX_NODE_INVERT,          0,          Invert,            "Invert Color",       "Add a Invert Texture node\nInverts the colors in the input image, producing a negative"              )
DefNode(TextureNode,     TEX_NODE_MATH,            def_math,            Math,              "Math",               "Add a Math Texture node\nPerforms math operations"              )
DefNode(TextureNode,     TEX_NODE_MIX_RGB,         def_mix_rgb,         MixRGB,            "Mix RGB",            "Add a Mix RGB Texture node\nMixes images by working on the individual and corresponding pixels of the two input images"              )
DefNode(TextureNode,     TEX_NODE_OUTPUT,          def_tex_output,          Output,            "Output",             "Add a Output Texture node\nOutput for node textures"              )
DefNode(TextureNode,     TEX_NODE_RGBTOBW,         0,         RGBToBW,           "RGB to BW",          "Add a RGB to BW Texture node\nConverts an RGB color image to a gray-scale image based at its luminance"              )
DefNode(TextureNode,     TEX_NODE_ROTATE,          0,          Rotate,            "Rotate",             "Add a Rotate Texture node\nRotate an image"              )
DefNode(TextureNode,     TEX_NODE_SCALE,           0,           Scale,             "Scale",              "Add a Scale Texture node\nScales the size of an image"              )
DefNode(TextureNode,     TEX_NODE_SEPARATE_COLOR,  def_tex_combsep_color,  SeparateColor,     "Separate Color",     "Add a Separate Color Texture node\nSeparates the values of a rgb, hsv or hsl color into its single values")
DefNode(TextureNode,     TEX_NODE_TEXTURE,         def_texture,         Texture,           "Texture",            "Add a Texture Texture node\nallows you to use 3D textures in the Compositor"              )
DefNode(TextureNode,     TEX_NODE_TRANSLATE,       0,       Translate,         "Translate",          "Add a Translate Texture node\nMove the texture"              )
DefNode(TextureNode,     TEX_NODE_VALTONOR,        0,        ValToNor,          "Value to Normal",    "Add a Value to Normal Texture node\nComputes a normal map"              )
DefNode(TextureNode,     TEX_NODE_VALTORGB,        def_colorramp,        ValToRGB,          "Color Ramp",         "Add a Color Ramp Texture node\nMaps values to colors with the use of a gradient"              )
DefNode(TextureNode,     TEX_NODE_VIEWER,          0,          Viewer,            "Viewer",             "Add a Viewer Texture node\nDisplays the output as a backdrop in the viewport or in the Image editor"              )
/* procedural textures */
DefNode(TextureNode,     TEX_NODE_PROC+TEX_BLEND,  0,       TexBlend,          "Blend",              "Add a Blend Texture node\nGenerates a smoothly interpolated progression"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_CLOUDS,  0,      TexClouds,         "Clouds",             "Add a Clouds Texture node\nAdds Perlin noise"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_DISTNOISE,  0,   TexDistNoise,      "Distorted Noise",    "Add a Distorted Noise Texture node\nGenerate distorted noise"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_MAGIC,  0,       TexMagic,          "Magic",              "Add a Magic Texture node\nAdds a procedural psychedelic color texture"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_MARBLE,  0,      TexMarble,         "Marble",             "Add a Marble Texture node\nGenerates marble, fire, or noise with a structure"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_MUSGRAVE,  0,    TexMusgrave,       "Musgrave",           "Add a Musgrave Texture node\nEvaluates a fractal Perlin noise at the input texture coordinates"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_NOISE,  0,       TexNoise,          "Noise",              "Add a Noise Texture node\nRandom generated noise"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_STUCCI,  0,      TexStucci,         "Stucci",             "Add a Stucci Texture node\nNoise based, but gives structures for stone, asphalt etc"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_VORONOI,  0,     TexVoronoi,        "Voronoi",            "Add a Voronoi Texture node\nEvaluates a Worley Noise at the input texture coordinates"              )
DefNode(TextureNode,     TEX_NODE_PROC+TEX_WOOD,  0,        TexWood,           "Wood",               "Add a Wood Texture node\nGenerate wood and ring-shaped patterns"              )

DefNode(FunctionNode, FN_NODE_ALIGN_EULER_TO_VECTOR, 0,  AlignEulerToVector,  "Align Euler to Vector",  "Add a Align Euler to Vector Function node\nAligns a euler value to a vector")
DefNode(FunctionNode, FN_NODE_ALIGN_ROTATION_TO_VECTOR, 0, AlignRotationToVector, "Align Rotation to Vector", "Add a Axes to Rotation Function node\nAligns a rotation to a vector")
DefNode(FunctionNode, FN_NODE_AXES_TO_ROTATION, 0, AxesToRotation, "Axes to Rotation", "Add a Rotation to Vector Function node\nCreate a rotation from a primary and (ideally orthogonal) secondary axis")
DefNode(FunctionNode, FN_NODE_AXIS_ANGLE_TO_ROTATION, 0, AxisAngleToRotation, "Axis Angle to Rotation", "Add a Axis Angle to Rotation Function node\nConverts a axis angle to a rotation vector")
DefNode(FunctionNode, FN_NODE_BOOLEAN_MATH, 0,  BooleanMath,  "Boolean Math",  "Add a Boolean Math Function node\nPerforms a basic logical operation between its inputs")
DefNode(FunctionNode, FN_NODE_COMBINE_COLOR, 0,  CombineColor,  "Combine Color",  "Add a Combine Color Function node\nCombines single colors to a rgb, hsv or hsl color value" )
DefNode(FunctionNode, FN_NODE_COMBINE_MATRIX, 0, CombineMatrix, "Combine Matrix", "Add a Combine Matrix Function node\nConstruct a 4x4 matrix from its individual values")
DefNode(FunctionNode, FN_NODE_COMBINE_TRANSFORM, 0, CombineTransform, "Combine Transform", "Add a Combine Transform Function node\n Combines the transform of matrices")
DefNode(FunctionNode, FN_NODE_COMPARE, 0,  Compare,  "Compare",     "Add a Compare Function node\nAdds a mathematical compare between two inputs")
DefNode(FunctionNode, FN_NODE_EULER_TO_ROTATION, 0, EulerToRotation, "Euler to Rotation", "Add a Euler to Rotation Function node\nConverts a euler angle to a rotation vector")
DefNode(FunctionNode, FN_NODE_FLOAT_TO_INT, def_float_to_int,  FloatToInt,  "Float to Integer",  "Add a Float to Integer Function node\nConverts float values into integer values")
DefNode(FunctionNode, FN_NODE_HASH_VALUE, 0, HashValue, "Hash Value", "Add a Hash Value node\nShows a hash value")
DefNode(FunctionNode, FN_NODE_INPUT_BOOL, def_fn_input_bool,  InputBool,  "Boolean",  "Add a Boolean Function node\nAdds a boolean that can be on or off")
DefNode(FunctionNode, FN_NODE_INPUT_COLOR, def_fn_input_color,  InputColor,  "Color",  "Add a Color Function node\nAdds a color picker that allows you to set a color")
DefNode(FunctionNode, FN_NODE_INPUT_INT, def_fn_input_int,  InputInt,  "Integer",  "Add a Integer Function node\nAllows to add a integer number")
DefNode(FunctionNode, FN_NODE_INPUT_ROTATION, def_fn_input_rotation, InputRotation, "Rotation", "Add a Rotation Function node\nAllows a constant rotation")
DefNode(FunctionNode, FN_NODE_INPUT_SPECIAL_CHARACTERS,  0,  InputSpecialCharacters,  "Special Characters",  "Add a Special Character Function node\nAdd special characters")
DefNode(FunctionNode, FN_NODE_INPUT_STRING, def_fn_input_string,  InputString,  "String",  "Add a String Function node\nAdds a string")
DefNode(FunctionNode, FN_NODE_INPUT_VECTOR, def_fn_input_vector,  InputVector,  "Vector",  "Add a Vector Function Function node\nCreates a single vector of three values that can be used as an input")
DefNode(FunctionNode, FN_NODE_INTEGER_MATH, 0, IntegerMath, "Integer Math", "Add a Integer Math node\nCreates a math node that works with integers")
DefNode(FunctionNode, FN_NODE_INVERT_MATRIX, 0, InvertMatrix, "Invert Matrix", "Add a Invert Matrix node\nInverts the matrix")
DefNode(FunctionNode, FN_NODE_INVERT_ROTATION, 0, InvertRotation, "Invert Rotation", "Add a Invert Rotation Function node\nInverts a rotation verctor")
DefNode(FunctionNode, FN_NODE_MATRIX_DETERMINANT, 0, MatrixDeterminant, "Matrix Determinant", "Add a Matrix Determinant node")
DefNode(FunctionNode, FN_NODE_MATRIX_MULTIPLY, 0, MatrixMultiply, "Multiply Matrices", "Add a Multiply Matrices Function node\nMultiplies the matrices")
DefNode(FunctionNode, FN_NODE_PROJECT_POINT, 0, ProjectPoint, "Project Point", "Add a Project Point Function node\nProject a point using a matrix, using location, rotation, scale, and perspective divide")
DefNode(FunctionNode, FN_NODE_QUATERNION_TO_ROTATION, 0, QuaternionToRotation, "Quaternion to Rotation", "Add a Quaternion to Rotation Function node\nConverts a axis angle to a rotation vector")
DefNode(FunctionNode, FN_NODE_RANDOM_VALUE, def_fn_random_value,  RandomValue,  "Random Value",  "Add a Random Value Function node\nAdds a random value")
DefNode(FunctionNode, FN_NODE_REPLACE_STRING, 0,  ReplaceString,  "Replace String",  "Add a Replace String Function node\nAllows you to replace a string")
DefNode(FunctionNode, FN_NODE_ROTATE_EULER, def_fn_rotate_euler,  RotateEuler,  "Rotate Euler",  "Add a Rotate Euler Function node\nRotate in euler angles")
DefNode(FunctionNode, FN_NODE_ROTATE_ROTATION, 0, RotateRotation, "Rotate Rotation",  "Add a Rotate Rotation node\nRotate euler by another euler angle")
DefNode(FunctionNode, FN_NODE_ROTATE_VECTOR, 0, RotateVector, "Rotate Vector", "Add a Rotate Vector Function node\nRotate by a rotation vector")
DefNode(FunctionNode, FN_NODE_ROTATION_TO_AXIS_ANGLE, 0, RotationToAxisAngle, "Rotation to Axis Angle", "Add a Rotation to Axis Angle Function node\nConverts a rotation vector to a axis angle")
DefNode(FunctionNode, FN_NODE_ROTATION_TO_EULER, 0, RotationToEuler, "Rotation to Euler", "Add a Rotation to Euler Function node\nConverts a rotation vector to an euler angle vector")
DefNode(FunctionNode, FN_NODE_ROTATION_TO_QUATERNION, 0, RotationToQuaternion, "Rotation to Quaternion", "Add a Rotation to Quaternion Function node\nConverts a rotation vector to an quaternion angle vector")
DefNode(FunctionNode, FN_NODE_SEPARATE_COLOR, 0,  SeparateColor,  "Separate Color",  "Add a Separate Color Function node\nSeparates the values of a rgb, hsv or hsl color into its single values" )
DefNode(FunctionNode, FN_NODE_SEPARATE_MATRIX, 0, SeparateMatrix, "Separate Matrix", "Add a Separate Matrix Function node\nSplit a 4x4 matrix into its individual values")
DefNode(FunctionNode, FN_NODE_SEPARATE_TRANSFORM, 0, SeparateTransform, "Separate Transform", "Add a Separate Transform node\nSeparates the transform values of matrices")
DefNode(FunctionNode, FN_NODE_SLICE_STRING, 0,  SliceString,  "Slice String",  "Add a Slice String Function node\nAllows to slice an input string")
DefNode(FunctionNode, FN_NODE_STRING_LENGTH, 0,  StringLength,  "String Length",  "Add a String Length Function node\nCalculate the length of a string")
DefNode(FunctionNode, FN_NODE_FIND_IN_STRING, 0, FindInString, "Find In String","")
DefNode(FunctionNode, FN_NODE_TRANSFORM_DIRECTION, 0, TransformDirection, "Transform Direction", "Add a Transform Direction node\nRetreive the transform direction")
DefNode(FunctionNode, FN_NODE_TRANSFORM_POINT, 0, TransformPoint, "Transform Point", "Add a Transform Point node\nRetreive the transform point")
DefNode(FunctionNode, FN_NODE_TRANSPOSE_MATRIX, 0, TransposeMatrix, "Transpose Matrix", "Add a Transpose Matrix node\nRetreive the transpose matrix")
DefNode(FunctionNode, FN_NODE_VALUE_TO_STRING, 0,  ValueToString,  "Value to String",  "Add a Value to String Function node\nConverts a value to a text string")

DefNode(GeometryNode, GEO_NODE_ACCUMULATE_FIELD, 0, AccumulateField, "Accumulate Field", "Add a Accumulate Field Geometry node\nAdd the values of an evaluated field together and output the running total for each element")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_DOMAIN_SIZE, 0, AttributeDomainSize, "Domain Size", "Add a Domain Size Geometry node\nRetrieve the number of elements in a geometry for each attribute domain")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_STATISTIC, 0,AttributeStatistic, "Attribute Statistic", "Add a Attribute Statistic Geometry node\nCalculate statistics about a data set from a field evaluated on a geometry")
DefNode(GeometryNode, GEO_NODE_BAKE, rna_def_geo_bake, Bake, "Bake", "Add a Bake Geometry node\nCache the incoming data so that it can be used without recomputation")
DefNode(GeometryNode, GEO_NODE_BLUR_ATTRIBUTE, 0, BlurAttribute, "Blur Attribute", "Add a Blur Attribute Geometry node\nMix attribute values of neighboring elements")
DefNode(GeometryNode, GEO_NODE_BOUNDING_BOX, 0, BoundBox, "Bounding Box", "Add a Bounding Box Geometry node\nCalculate the limits of a geometry's positions and generate a box mesh with those dimensions")
DefNode(GeometryNode, GEO_NODE_CAPTURE_ATTRIBUTE, rna_def_geo_capture_attribute, CaptureAttribute, "Capture Attribute", "Add a Capture Attribute Geometry node\nStore the result of a field on a geometry and output the data as a node socket. Allows remembering or interpolating data as the geometry changes, such as positions before deformation")
DefNode(GeometryNode, GEO_NODE_COLLECTION_INFO, 0, CollectionInfo, "Collection Info", "Add a Collection Info Geometry node\nRetrieve geometry instances from a collection")
DefNode(GeometryNode, GEO_NODE_CONVEX_HULL, 0, ConvexHull, "Convex Hull", "Add a Convex Hull Geometry node\nCreate a mesh that encloses all points in the input geometry with the smallest number of points")
DefNode(GeometryNode, GEO_NODE_CURVE_ENDPOINT_SELECTION, 0, CurveEndpointSelection, "Endpoint Selection", "Add a Endpoint Selection Geometry node\nProvide a selection for an arbitrary number of endpoints in each spline")
DefNode(GeometryNode, GEO_NODE_CURVE_HANDLE_TYPE_SELECTION, def_geo_curve_handle_type_selection, CurveHandleTypeSelection, "Handle Type Selection", "Add a Handle Type Selection Geometry node\nProvide a selection based on the handle types of Bézier control points")
DefNode(GeometryNode, GEO_NODE_CURVE_LENGTH, 0, CurveLength, "Curve Length", "Add a Curve Length Geometry node\nRetrieve the length of all splines added together")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_ARC, 0,CurveArc, "Arc", "Add a Arc Geometry node\nGenerate a poly spline arc")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_BEZIER_SEGMENT, 0, CurvePrimitiveBezierSegment, "Bézier Segment", "Add a Bezier Segment Geometry node\nGenerate a 2D Bézier spline from the given control points and handles")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_CIRCLE,0, CurvePrimitiveCircle, "Curve Circle", "Add a Curve Circle Geometry node\nGenerate a poly spline circle")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_LINE, 0, CurvePrimitiveLine, "Curve Line", "Add a Curve Line Geometry node\nGenerate a poly spline line with two points")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_QUADRATIC_BEZIER, 0, CurveQuadraticBezier, "Quadratic Bézier", "Add a Quadratic Bezier Geometry node\nGenerate a poly spline in a parabola shape with control points positions")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_QUADRILATERAL, 0, CurvePrimitiveQuadrilateral, "Quadrilateral", "Add a Curve Quadrilateral node\nGenerate a polygon with four points")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_SPIRAL,0, CurveSpiral, "Spiral", "Add a Spiral Geometry node\nGenerate a poly spline in a spiral shape")
DefNode(GeometryNode, GEO_NODE_CURVE_PRIMITIVE_STAR, 0, CurveStar, "Star", "Add a Star Geometry node\nGenerate a poly spline in a star pattern by connecting alternating points of two circles")
DefNode(GeometryNode, GEO_NODE_CURVE_SET_HANDLE_TYPE, def_geo_curve_set_handle_type, CurveSetHandles, "Set Handle Type", "Add a Set Handle Type Geometry node\nSet the handle type for the control points of a Bézier curve")
DefNode(GeometryNode, GEO_NODE_CURVE_SPLINE_PARAMETER,0, SplineParameter, "Spline Parameter", "Add a Spline Parameter Geometry node\nRetrieve how far along each spline a control point is")
DefNode(GeometryNode, GEO_NODE_CURVE_SPLINE_TYPE, 0, CurveSplineType, "Set Spline Type", "Add a Set Spline Type Geometry node\nChange the type of curves")
DefNode(GeometryNode, GEO_NODE_CURVE_TO_MESH, 0, CurveToMesh, "Curve to Mesh", "Add a Curve to Mesh Geometry node\nConvert curves into a mesh, optionally with a custom profile shape defined by curves")
DefNode(GeometryNode, GEO_NODE_CURVE_TO_POINTS, 0, CurveToPoints, "Curve to Points", "Add a Curve to Points Geometry node\nGenerate a point cloud by sampling positions along curves")
DefNode(GeometryNode, GEO_NODE_CURVE_TOPOLOGY_CURVE_OF_POINT, 0, CurveOfPoint, "Curve of Point", "Add a Curve of Point Geometry node\nRetrieve the curve a control point is part of")
DefNode(GeometryNode, GEO_NODE_CURVE_TOPOLOGY_POINTS_OF_CURVE, 0, PointsOfCurve, "Points of Curve", "Add a Points of Curve Geometry node\nRetrieve a point index within a curve")
DefNode(GeometryNode, GEO_NODE_CURVES_TO_GREASE_PENCIL, 0, CurvesToGreasePencil, "Curves to Grease Pencil", "Add Curves to Grease Pencil node\nConvert the curves in each top-level instance into Grease Pencil layer")
DefNode(GeometryNode, GEO_NODE_DEFORM_CURVES_ON_SURFACE, 0, DeformCurvesOnSurface, "Deform Curves on Surface", "Add a Deform Curves on Surface Geometry node\nTranslate and rotate curves based on changes between the object's original and evaluated surface mesh")
DefNode(GeometryNode, GEO_NODE_DELETE_GEOMETRY, 0, DeleteGeometry, "Delete Geometry", "Add a Delete Geometry Geometry node\nRemove selected elements of a geometry")
DefNode(GeometryNode, GEO_NODE_DISTRIBUTE_POINTS_IN_GRID, 0, DistributePointsInGrid, "Distribute Points in Grid", "Add a Distribute Points in Grid node\nRGenerate points inside a volume grid")
DefNode(GeometryNode, GEO_NODE_DISTRIBUTE_POINTS_IN_VOLUME, 0, DistributePointsInVolume, "Distribute Points in Volume", "Add a Distribute Points in Volume Geometry node\nGenerate points inside a volume")
DefNode(GeometryNode, GEO_NODE_DISTRIBUTE_POINTS_ON_FACES, def_geo_distribute_points_on_faces, DistributePointsOnFaces, "Distribute Points on Faces", "Add a Distribute Points on Faces Geometry node\nGenerate points spread out on the surface of a mesh")
DefNode(GeometryNode, GEO_NODE_DUAL_MESH, 0, DualMesh, "Dual Mesh", "Add a Dual Mesh Geometry node\nConvert Faces into vertices and vertices into faces")
DefNode(GeometryNode, GEO_NODE_DUPLICATE_ELEMENTS, 0, DuplicateElements,  "Duplicate Elements",  "Add a Duplicate Elements Geometry Node\nDuplicates the selected mesh element")
DefNode(GeometryNode, GEO_NODE_EDGE_PATHS_TO_CURVES, 0, EdgePathsToCurves, "Edge Paths to Curves", "Add a Edge Paths to Curves Geometry Node\nConverts Edge Paths to curves")
DefNode(GeometryNode, GEO_NODE_EDGE_PATHS_TO_SELECTION, 0, EdgePathsToSelection, "Edge Paths to Selection", "Add a Edge Paths to Selection Geometry Node\nDefines a edge path with given input vertices and converts it to a selection")
DefNode(GeometryNode, GEO_NODE_EDGES_TO_FACE_GROUPS, 0, EdgesToFaceGroups, "Edges to Face Groups", "Add a Edges to Face Groups Geometry Node\nGroup faces into regions surrounded by the selected boundary edges")
DefNode(GeometryNode, GEO_NODE_EVALUATE_AT_INDEX, 0, FieldAtIndex, "Evaluate at Index", "Add a Evaluate at Index Geometry Node\nRetrieve data of other elements in the context's geometry")
DefNode(GeometryNode, GEO_NODE_EVALUATE_ON_DOMAIN, 0, FieldOnDomain, "Evaluate on Domain", "Add a Evaluate on Domain Geometry Node\nRRetrieve values from a field on a different domain besides the domain from the context")
DefNode(GeometryNode, GEO_NODE_EXTRUDE_MESH, 0, ExtrudeMesh, "Extrude Mesh", "Add a Extrude Mesh Geometry node\nGenerate new vertices, edges, or faces from selected elements and move them based on an offset while keeping them connected by their boundary")
DefNode(GeometryNode, GEO_NODE_FILL_CURVE, 0, FillCurve, "Fill Curve", "Add a Fill Curve Geometry node\nGenerate a mesh on the XY plane with faces on the inside of input curves")
DefNode(GeometryNode, GEO_NODE_FILLET_CURVE, 0, FilletCurve, "Fillet Curve", "Add a Fillet Curve Geometry node\nRound corners by generating circular arcs on each control point")
DefNode(GeometryNode, GEO_NODE_FLIP_FACES, 0, FlipFaces, "Flip Faces", "Add a Flip Faces Geometry node\nReverse the order of the vertices and edges of selected faces, flipping their normal direction")
DefNode(GeometryNode, GEO_NODE_FOREACH_GEOMETRY_ELEMENT_INPUT, def_geo_foreach_geometry_element_input, ForeachGeometryElementInput, "For Each Element Input", "Add a For Each Element Input node\nFor Each Geometry Element Input used to start a series of operations for each element")
DefNode(GeometryNode, GEO_NODE_FOREACH_GEOMETRY_ELEMENT_OUTPUT, def_geo_foreach_geometry_element_output, ForeachGeometryElementOutput, "For Each Element Output", "Add a For Each Element Output node\nFor Each Geometry Element Output used to end a series of operations for each element")
DefNode(GeometryNode, GEO_NODE_GEOMETRY_TO_INSTANCE, 0, GeometryToInstance, "Geometry to Instance", "Add a Geometry to Instance Geometry node\nConvert each input geometry into an instance, which can be much faster than the Join Geometry node when the inputs are large")
DefNode(GeometryNode, GEO_NODE_GET_NAMED_GRID, 0, GetNamedGrid, "Get Named Grid", "Add a Get Named Grid node\nGet volume grid from a volume geometry with the specified name")
DefNode(GeometryNode, GEO_NODE_GIZMO_DIAL, 0, GizmoDial, "Dial Gizmo", "Add a Dial Gizmo node\nShow a dial gizmo in the viewport for a value")
DefNode(GeometryNode, GEO_NODE_GIZMO_LINEAR, 0, GizmoLinear, "Linear Gizmo", "Add a Linear Gizmo node\nShow a linear gizmo in the viewport for a value")
DefNode(GeometryNode, GEO_NODE_GIZMO_TRANSFORM, rna_def_geo_gizmo_transform, GizmoTransform, "Transform Gizmo", "Add a Transform Gizmo node\nShow a transform gizmo in the viewport")
DefNode(GeometryNode, GEO_NODE_GREASE_PENCIL_TO_CURVES, 0, GreasePencilToCurves, "Grease Pencil to Curves", "Add Grease Pencil to Curves node\nConvert Grease Pencil layers into curve instances")
DefNode(GeometryNode, GEO_NODE_GRID_TO_MESH, 0, GridToMesh, "Grid to Mesh", "Add a Grid to Mesh node\nGenerate a mesh on the \"surface\" of a volume grid")
DefNode(GeometryNode, GEO_NODE_IMAGE_INFO, 0, ImageInfo, "Image Info", "Add an Image Info Geometry node\nRetrieve information about an image")
DefNode(GeometryNode, GEO_NODE_IMAGE_TEXTURE, def_geo_image_texture, ImageTexture, "Image Texture", "Add an Image Texture node\nSample values from an image texture")
DefNode(GeometryNode, GEO_NODE_IMAGE, def_geo_image, InputImage, "Image", "Add an Image Input node\nInput image")
DefNode(GeometryNode, GEO_NODE_IMPORT_OBJ, 0, ImportOBJ, "Import OBJ", "Add an Import OBJ node\nImport geometry from an OBJ file")
DefNode(GeometryNode, GEO_NODE_IMPORT_PLY, 0, ImportPLY, "Import PLY", "Add an Import PLY node\nImport a point cloud from a PLY file")
DefNode(GeometryNode, GEO_NODE_IMPORT_STL, 0, ImportSTL, "Import STL", "Add an Import STL node\nImport a mesh from an STL file")
DefNode(GeometryNode, GEO_NODE_INDEX_OF_NEAREST, 0, IndexOfNearest, "Index of Nearest", "Add an Index of Nearest node\nFind the nearest element in a group. Similar to the \"Sample Nearest\" node")
DefNode(GeometryNode, GEO_NODE_INDEX_SWITCH, def_geo_index_switch, IndexSwitch, "Index Switch", "Add an Index Switch node\nChoose between an arbitrary number of values with an index")
DefNode(GeometryNode, GEO_NODE_INPUT_ACTIVE_CAMERA, 0, InputActiveCamera, "Active Camera", "Add an Active Camera node\nRetrieve the scene's active camera")
DefNode(GeometryNode, GEO_NODE_INPUT_COLLECTION, def_geo_input_collection, InputCollection, "Collection", "Add an Input Collection node\nOutput a single collection")
DefNode(GeometryNode, GEO_NODE_INPUT_CURVE_HANDLES, 0, InputCurveHandlePositions, "Curve Handle Positions", "Add a Curve Handle Positions node\nRetrieve the position of each Bézier control point's handles")
DefNode(GeometryNode, GEO_NODE_INPUT_CURVE_TILT, 0, InputCurveTilt, "Curve Tilt", "Add a Curve Tilt node\nRetrieve the angle at each control point used to twist the curve's normal around its tangent")
DefNode(GeometryNode, GEO_NODE_INPUT_EDGE_SMOOTH, 0, InputEdgeSmooth, "Is Edge Smooth", "Add a Is Edge Smooth node\nSRetrieve whether each edge is marked for smooth or split normals")
DefNode(GeometryNode, GEO_NODE_INPUT_FACE_SMOOTH, 0, InputShadeSmooth, "Is Face Smooth", "Add a Is Shade Smooth node\nRetrieve whether each face is marked for smooth or sharp normals")
DefNode(GeometryNode, GEO_NODE_INPUT_ID, 0, InputID, "ID", "Add an ID node\nRetrieve a stable random identifier value from the \"id\" attribute on the point domain, or the index if the attribute does not exist")
DefNode(GeometryNode, GEO_NODE_INPUT_INDEX, 0, InputIndex, "Index", "Add a Index node\nRetrieve an integer value indicating the position of each element in the list, starting at zero")
DefNode(GeometryNode, GEO_NODE_INPUT_INSTANCE_ROTATION, 0, InputInstanceRotation, "Instance Rotation", "Add a Instance Rotation node\nRetrieve the rotation of each instance in the geometry")
DefNode(GeometryNode, GEO_NODE_INPUT_INSTANCE_SCALE, 0, InputInstanceScale, "Instance Scale", "Add a Instanec Scale node\nRetrieve the scale of each instance in the geometry")
DefNode(GeometryNode, GEO_NODE_INPUT_INSTANCE_TRANSFORM, 0, InstanceTransform, "Instance Transform", "Add a Instance Transform node\nRetrieve the full transformation of each instance in the geometry")
DefNode(GeometryNode, GEO_NODE_INPUT_MATERIAL_INDEX, 0, InputMaterialIndex, "Material Index", "Add a Material Index node\nRetrieve the index of the material used for each element in the geometry's list of materials")
DefNode(GeometryNode, GEO_NODE_INPUT_MATERIAL, def_geo_input_material, InputMaterial, "Material", "Add a Material node\nOutput a single material")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_EDGE_ANGLE, 0, InputMeshEdgeAngle, "Edge Angle", "Add an Edge Angle node\nThe angle between the normals of connected manifold faces")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_EDGE_NEIGHBORS, 0,InputMeshEdgeNeighbors, "Edge Neighbors", "Add an Edge neighbors node\nRetrieve the number of faces that use each edge as one of their sides")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_EDGE_VERTICES, 0, InputMeshEdgeVertices, "Edge Vertices", "Add an Edge Vertices node\nRetrieve topology information relating to each edge of a mesh")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_FACE_AREA, 0, InputMeshFaceArea, "Face Area", "Add a Face Area node\nCalculate the surface area of a mesh's faces")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_FACE_IS_PLANAR, 0, InputMeshFaceIsPlanar, "Is Face Planar", "Add a Is Face Planar node\nRetrieve whether all triangles in a face are on the same plane, i.e. whether they have the same normal")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_FACE_NEIGHBORS, 0,InputMeshFaceNeighbors, "Face Neighbors", "Add a Face Neighbors node\nRetrieve topology information relating to each face of a mesh")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_ISLAND, 0, InputMeshIsland, "Mesh Island", "Add a Mesh Island node\nRetrieve information about separate connected regions in a mesh")
DefNode(GeometryNode, GEO_NODE_INPUT_MESH_VERTEX_NEIGHBORS, 0, InputMeshVertexNeighbors, "Vertex Neighbors", "Add a Vertex Neighbors node\nRetrieve topology information relating to each vertex of a mesh")
DefNode(GeometryNode, GEO_NODE_INPUT_NAMED_ATTRIBUTE, 0, InputNamedAttribute, "Named Attribute", "Add a Named Attributes node\nRetrieve the data of a specified attribute")
DefNode(GeometryNode, GEO_NODE_INPUT_NAMED_LAYER_SELECTION, 0, InputNamedLayerSelection, "Named Layer Selection", "Add a Layere Selection Node\nOutput a selection of a Grease Pencil layer")
DefNode(GeometryNode, GEO_NODE_INPUT_NORMAL, 0, InputNormal, "Normal", "Add a Normal node\nRetrieve a unit length vector indicating the direction pointing away from the geometry at each element")
DefNode(GeometryNode, GEO_NODE_INPUT_OBJECT, def_geo_input_object, InputObject, "Object", "Add an Object Input node\nOutput a single object")
DefNode(GeometryNode, GEO_NODE_INPUT_POSITION, 0, InputPosition, "Position", "Add a Position node\nRetrieve a vector indicating the location of each element")
DefNode(GeometryNode, GEO_NODE_INPUT_RADIUS, 0, InputRadius, "Radius", "Add a Radius node\nRetrieve the radius at each point on curve or point cloud geometry")
DefNode(GeometryNode, GEO_NODE_INPUT_SCENE_TIME, 0, InputSceneTime, "Scene Time", "Add a Scene Time node\nRetrieve the current time in the scene's animation in units of seconds or frames")
DefNode(GeometryNode, GEO_NODE_INPUT_SHORTEST_EDGE_PATHS, 0, InputShortestEdgePaths, "Shortest Edge Paths", "Add a Shortest Edge Paths node\n Retrieve the shortest edge paths on select geometry")
DefNode(GeometryNode, GEO_NODE_INPUT_SPLINE_CYCLIC, 0,InputSplineCyclic, "Is Spline Cyclic", "Add a Is Spline Cyclic node\nRetrieve whether each spline endpoint connects to the beginning")
DefNode(GeometryNode, GEO_NODE_INPUT_SPLINE_LENGTH, 0, SplineLength, "Spline Length", "Add a Spline Length node\nRetrieve the total length of each spline, as a distance or as a number of points")
DefNode(GeometryNode, GEO_NODE_INPUT_SPLINE_RESOLUTION, 0, InputSplineResolution, "Spline Resolution", "Add a Spline Resolution node\nRetrieve the number of evaluated points that will be generated for every control point on curves")
DefNode(GeometryNode, GEO_NODE_INPUT_TANGENT, 0, InputTangent, "Curve Tangent", "Add a Curve Tangent node\nRetrieve the direction of curves at each control point")
DefNode(GeometryNode, GEO_NODE_INSTANCE_ON_POINTS, 0, InstanceOnPoints, "Instance on Points", "Add a Instance on Points node\nGenerate a reference to geometry at each of the input points, without duplicating its underlying data")
DefNode(GeometryNode, GEO_NODE_INSTANCES_TO_POINTS, 0,InstancesToPoints, "Instances to Points", "Add a Instances to Points node\nGenerate points at the origins of instances.\nNote: Nested instances are not affected by this node")
DefNode(GeometryNode, GEO_NODE_INTERPOLATE_CURVES, 0, InterpolateCurves, "Interpolate Curves", "Add a Interpolate Curves node\nGenerate new curves on points by interpolating between existing curves")
DefNode(GeometryNode, GEO_NODE_IS_VIEWPORT, 0, IsViewport, "Is Viewport", "Add a Is Viewport node\nRetrieve whether the nodes are being evaluated for the viewport rather than the final render")
DefNode(GeometryNode, GEO_NODE_JOIN_GEOMETRY, 0, JoinGeometry, "Join Geometry", "Add a Join Geometry node\nMerge separately generated geometries into a single one")
DefNode(GeometryNode, GEO_NODE_MATERIAL_SELECTION, 0, MaterialSelection, "Add a Material Selection node", "Add a Material Selection node\nProvide a selection of faces that use the specified material")
DefNode(GeometryNode, GEO_NODE_MENU_SWITCH, def_geo_menu_switch, MenuSwitch, "Menu Switch", "Add a Menu Switch node\nSelect from multiple inputs by name")
DefNode(GeometryNode, GEO_NODE_MERGE_BY_DISTANCE, 0, MergeByDistance, "Merge by Distance", "Add a Merge by Distance Geometry node\nMerge vertices or points within a given distance")
DefNode(GeometryNode, GEO_NODE_MERGE_LAYERS, 0, MergeLayers, "Merge Layers", "Add a Merge Layers node\nJoin groups of Grease Pencil layers into one")
DefNode(GeometryNode, GEO_NODE_MESH_BOOLEAN, 0, MeshBoolean, "Mesh Boolean", "Add a Mesh Boolean Geometry node\nCut, subtract, or join multiple mesh inputs")
DefNode(GeometryNode, GEO_NODE_MESH_FACE_GROUP_BOUNDARIES, 0, MeshFaceSetBoundaries, "Face Group Boundaries", "Add a Face Group Boundaries Geometry node\nFind edges on the boundaries between groups of faces with the same ID value")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CIRCLE, 0, MeshCircle, "Mesh Circle", "Add a Mesh Circle Geometry node\nGenerate a circular ring of edges")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CONE, 0,MeshCone, "Cone", "Add a Cone Geometry node\nGenerate a cone mesh")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CUBE, 0,MeshCube, "Cube", "Add a Cube Geometry node\nGenerate a cuboid mesh with variable side lengths and subdivisions")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CYLINDER, 0, MeshCylinder, "Cylinder", "Add a Cylinder Geometry node\nGenerate a cylinder mesh")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_GRID, 0,MeshGrid, "Grid", "Add a Grid Geometry node\nGenerate a planar mesh on the XY plane")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_ICO_SPHERE, 0, MeshIcoSphere, "Ico Sphere", "Add a Ico Sphere Geometry node\nGenerate a spherical mesh that consists of equally sized triangles")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_LINE, 0,MeshLine, "Mesh Line", "Add a Mesh Line Geometry node\nGenerate vertices in a line and connect them with edges")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_UV_SPHERE, 0, MeshUVSphere, "UV Sphere", "Add a UV Sphere Geometry node\nGenerate a spherical mesh with quads, except for triangles at the top and bottom")
DefNode(GeometryNode, GEO_NODE_MESH_TO_CURVE, 0, MeshToCurve, "Mesh to Curve", "Add a Mesh to Curve Geometry node\nGenerate a curve from a mesh")
DefNode(GeometryNode, GEO_NODE_MESH_TO_DENSITY_GRID, 0, MeshToDensityGrid, "Mesh to Density Grid", "Add a Mesh to Density Grid node\nCreate a filled volume grid from a mesh")
DefNode(GeometryNode, GEO_NODE_MESH_TO_POINTS, 0, MeshToPoints, "Mesh to Points", "Add a Mesh to Points Geometry node\nGenerate a point cloud from a mesh's vertices")
DefNode(GeometryNode, GEO_NODE_MESH_TO_SDF_GRID, 0, MeshToSDFGrid, "Mesh to SDF Grid", "Add a Mesh to SDF Grid node\nCreate a signed distance volume grid from a mesh")
DefNode(GeometryNode, GEO_NODE_MESH_TO_VOLUME, 0, MeshToVolume, "Mesh to Volume", "Add a Mesh to Volume Geometry node\nCreate a fog volume with the shape of the input mesh's surface")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_CORNERS_OF_EDGE, 0, CornersOfEdge, "Corners of Edge", "Add a Corners of Edge Geometry node\nRetrieve face corners connected to edges")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_CORNERS_OF_FACE, 0, CornersOfFace, "Corners of Face", "Add a Corners of Face Geometry node\nRetrieve corners that make up a face")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_CORNERS_OF_VERTEX, 0, CornersOfVertex, "Corners of Vertex", "Add a Corners of Vertex Geometry node\nRetrieve face corners connected to vertices")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_EDGES_OF_CORNER, 0, EdgesOfCorner, "Edges of Corner", "Add a Edges of Corner Geometry node\nRetrieve the edges on both sides of a face corner")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_EDGES_OF_VERTEX, 0, EdgesOfVertex, "Edges of Vertex", "Add a Edges of Vertex Geometry node\nRetrieve the edges connected to each vertex")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_FACE_OF_CORNER, 0, FaceOfCorner, "Face of Corner", "Add a Face of Corner Geometry node\nRetrieve the face each face corner is part of")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_OFFSET_CORNER_IN_FACE, 0, OffsetCornerInFace, "Offset Corner in Face", "Add a Offset Corner in Face Geometry node\nRetrieve corners in the same face as another")
DefNode(GeometryNode, GEO_NODE_MESH_TOPOLOGY_VERTEX_OF_CORNER, 0, VertexOfCorner, "Vertex of Corner", "Add a Vertex of Corner Geometry node\nRetrieve the vertex each face corner is attached to")
DefNode(GeometryNode, GEO_NODE_OBJECT_INFO, 0, ObjectInfo, "Object Info", "Add a Object Info Geometry node\nRetrieve information from an object")
DefNode(GeometryNode, GEO_NODE_OFFSET_POINT_IN_CURVE, 0, OffsetPointInCurve, "Offset Point in Curve", "Add a Offset Point in Curve Geometry node\nOffset a control point index within its curve")
DefNode(GeometryNode, GEO_NODE_POINTS_TO_CURVES, 0, PointsToCurves, "Points to Curves", "Add a Points to Curves node\nSplit all points to curve by its group ID and reorder by weight")
DefNode(GeometryNode, GEO_NODE_POINTS_TO_SDF_GRID, 0, PointsToSDFGrid, "Points to SDF Grid", "Add a Points to SDF Grid node\nCreate a signed distance volume grid from points")
DefNode(GeometryNode, GEO_NODE_POINTS_TO_VERTICES, 0, PointsToVertices, "Points to Vertices", "Add a Points to Vertices Geometry node\nGenerate a mesh vertex for each point cloud point")
DefNode(GeometryNode, GEO_NODE_POINTS_TO_VOLUME, 0, PointsToVolume, "Points to Volume", "Add a Points to Volume Geometry node\nGenerate a fog volume sphere around every point")
DefNode(GeometryNode, GEO_NODE_POINTS, 0, Points, "Points", "Add a Points Geometry node\nGenerate a point cloud with positions and radii defined by fields")
DefNode(GeometryNode, GEO_NODE_PROXIMITY, 0, Proximity, "Geometry Proximity", "Add a Switch Geometry node\nCompute the closest location on the target geometry")
DefNode(GeometryNode, GEO_NODE_RAYCAST, 0, Raycast, "Raycast", "Add a Raycast Geometry node\nCast rays from the context geometry onto a target geometry, and retrieve information from each hit point")
DefNode(GeometryNode, GEO_NODE_REALIZE_INSTANCES, 0, RealizeInstances, "Realize Instances", "Add a Realize Instances Geometry node\nConvert instances into real geometry data")
DefNode(GeometryNode, GEO_NODE_REMOVE_ATTRIBUTE, 0, RemoveAttribute, "Remove Named Attribute", "Add a Remove Named Attribute Geometry node\nDelete an attribute with a specified name from a geometry. Typically used to optimize performance")
DefNode(GeometryNode, GEO_NODE_REPEAT_INPUT, def_geo_repeat_input, RepeatInput, "Repeat Input", "Add a Repeat Input  Geometry node\nStarts a serial loop for a chain of nodes a number of times")
DefNode(GeometryNode, GEO_NODE_REPEAT_OUTPUT, def_geo_repeat_output, RepeatOutput, "Repeat Output", "Add a Repeat Output Geometry node\nEnds a serial loop for a chain of nodes a number of times")
DefNode(GeometryNode, GEO_NODE_REPLACE_MATERIAL, 0, ReplaceMaterial, "Replace Material", "Add a Replace Material Geometry node\n\nSwap one material with another")
DefNode(GeometryNode, GEO_NODE_RESAMPLE_CURVE, 0, ResampleCurve, "Resample Curve", "Add a Resample Curve Geometry node\nGenerate a poly spline for each input spline")
DefNode(GeometryNode, GEO_NODE_REVERSE_CURVE, 0, ReverseCurve, "Reverse Curve", "Add a Reverse Curve Geometry node\nChange the direction of curves by swapping their start and end data")
DefNode(GeometryNode, GEO_NODE_ROTATE_INSTANCES, 0, RotateInstances, "Rotate Instances", "Add a Rotate Instances Geometry node\nRotate geometry instances in local or global space")
DefNode(GeometryNode, GEO_NODE_SAMPLE_CURVE, def_geo_curve_sample, SampleCurve, "Sample Curve", "Add a Sample Curve Geometry node\nRetrieve data from a point on a curve at a certain distance from its start")
DefNode(GeometryNode, GEO_NODE_SAMPLE_GRID_INDEX, 0, SampleGridIndex, "Sample Grid Index", "Add a Sample Grid Index node\nRetrieve volume grid values at specific voxels")
DefNode(GeometryNode, GEO_NODE_SAMPLE_GRID, 0, SampleGrid, "Sample Grid", "")
DefNode(GeometryNode, GEO_NODE_SAMPLE_INDEX, def_geo_sample_index, SampleIndex, "Sample Index", "Add a Sample Index Geometry node\nRetrieve values from specific geometry elements")
DefNode(GeometryNode, GEO_NODE_SAMPLE_NEAREST_SURFACE, 0, SampleNearestSurface, "Sample Nearest Surface", "Add a Sample Nearest Surface Geometry node\nCalculate the interpolated value of a mesh attribute on the closest point of its surface")
DefNode(GeometryNode, GEO_NODE_SAMPLE_NEAREST, 0, SampleNearest, "Sample Nearest", "Add a Sample Nearest Geometry node\nFind the element of a geometry closest to a position. Similar to the \"Index of Nearest\" node")
DefNode(GeometryNode, GEO_NODE_SAMPLE_UV_SURFACE, 0, SampleUVSurface, "Sample UV Surface", "Add a Sample UV Surface Geometry node\nCalculate the interpolated values of a mesh attribute at a UV coordinate")
DefNode(GeometryNode, GEO_NODE_SCALE_ELEMENTS, 0, ScaleElements, "Scale Elements", "Add a Scale Elements Geometry node\nScale groups of connected edges and faces")
DefNode(GeometryNode, GEO_NODE_SCALE_INSTANCES, 0, ScaleInstances, "Scale Instances", "Add a Scale Instances Geometry node\nScale geometry instances in local or global space")
DefNode(GeometryNode, GEO_NODE_SDF_GRID_BOOLEAN, 0, SDFGridBoolean, "SDF Grid Boolean", "Add a SDF Grid Boolean node\nCut, subtract, or join multiple SDF volume grid inputs")
DefNode(GeometryNode, GEO_NODE_SELF_OBJECT, 0, SelfObject, "Self Object", "Add a Self Object Geometry node\nRetrieve the object that contains the geometry nodes modifier currently being executed")
DefNode(GeometryNode, GEO_NODE_SEPARATE_COMPONENTS, 0,SeparateComponents, "Separate Components", "Add a Separate Components Geometry node\nSplit a geometry into a separate output for each type of data in the geometry")
DefNode(GeometryNode, GEO_NODE_SEPARATE_GEOMETRY, 0, SeparateGeometry, "Separate Geometry", "Add a Separate Geometry Geometry node\nSplit a geometry into two geometry outputs based on a selection")
DefNode(GeometryNode, GEO_NODE_SET_CURVE_HANDLES, 0, SetCurveHandlePositions, "Set Handle Positions", "Add a Set Handle Positions Geometry node\nSet the positions for the handles of Bézier curves")
DefNode(GeometryNode, GEO_NODE_SET_CURVE_NORMAL, 0, SetCurveNormal, "Set Curve Normal", "Add a Set Curve Normal Geometry node\nSet the evaluation mode for curve normals")
DefNode(GeometryNode, GEO_NODE_SET_CURVE_RADIUS, 0, SetCurveRadius, "Set Curve Radius", "Add a Set Curve Radius Geometry node\nSet the radius of the curve at each control point")
DefNode(GeometryNode, GEO_NODE_SET_CURVE_TILT, 0, SetCurveTilt, "Set Curve Tilt", "Add a Set Curve Tilt Geometry node\nSet the tilt angle at each curve control point")
DefNode(GeometryNode, GEO_NODE_SET_GEOMETRY_NAME, 0, SetGeometryName, "Set Geometry Name", "Add a Set Geometry Name node\nSet the name of a geometry for easier debugging")
DefNode(GeometryNode, GEO_NODE_SET_ID, 0, SetID, "Set ID", "Add a Set ID Geometry node\nSet the id attribute on the input geometry, mainly used internally for randomizing")
DefNode(GeometryNode, GEO_NODE_SET_INSTANCE_TRANSFORM, 0, SetInstanceTransform, "Set Instance Transform", "Add a Set Instance Transform node\nSet the transformation matrix of every instance")
DefNode(GeometryNode, GEO_NODE_SET_MATERIAL_INDEX, 0, SetMaterialIndex, "Set Material Index", "Add a Set Material Index Geometry node\nSet the material index for each selected geometry element")
DefNode(GeometryNode, GEO_NODE_SET_MATERIAL, 0, SetMaterial, "Set Material", "Add a Set Material Geometry node\nAssign a material to geometry elements")
DefNode(GeometryNode, GEO_NODE_SET_POINT_RADIUS, 0, SetPointRadius, "Set Point Radius", "Add a Set Point Radius Geometry node\nSet the display size of point cloud points")
DefNode(GeometryNode, GEO_NODE_SET_POSITION, 0, SetPosition, "Set Position", "Add a Set Position Geometry node\nSet the location of each point")
DefNode(GeometryNode, GEO_NODE_SET_SHADE_SMOOTH, 0, SetShadeSmooth, "Set Shade Smooth", "Add a Set Shade Smooth Geometry node\nControl the smoothness of mesh normals around each face by changing the \"shade smooth\" attribute")
DefNode(GeometryNode, GEO_NODE_SET_SPLINE_CYCLIC, 0, SetSplineCyclic, "Set Spline Cyclic", "Add a Set Spline Cyclic Geometry node\nControl whether each spline loops back on itself by changing the \"cyclic\" attribute")
DefNode(GeometryNode, GEO_NODE_SET_SPLINE_RESOLUTION, 0, SetSplineResolution, "Set Spline Resolution", "Add a Set Spline Resolution Geometry node\nControl how many evaluated points should be generated on every curve segment")
DefNode(GeometryNode, GEO_NODE_SIMULATION_INPUT, def_geo_simulation_input, SimulationInput, "Simulation Input", "Add a Simulation Input Geometry node\nInput data for the simulation zone")
DefNode(GeometryNode, GEO_NODE_SIMULATION_OUTPUT, def_geo_simulation_output, SimulationOutput, "Simulation Output", "Add a Simulation Output Geometry node\nOutput data from the simulation zone")
DefNode(GeometryNode, GEO_NODE_SORT_ELEMENTS, 0, SortElements, "Sort Elements", "Add a Sort Elements node\nRearrange geometry elements, changing their indices")
DefNode(GeometryNode, GEO_NODE_SPLIT_EDGES, 0, SplitEdges, "Split Edges", "Add a Split Edges Geometry node\nDuplicate mesh edges and break connections with the surrounding faces")
DefNode(GeometryNode, GEO_NODE_SPLIT_TO_INSTANCES, 0, SplitToInstances, "Split to Instances", "Add a Split to Instances Geometry node\nCreate separate geometries containing the elements from the same group")
DefNode(GeometryNode, GEO_NODE_STORE_NAMED_ATTRIBUTE, 0, StoreNamedAttribute, "Store Named Attribute", "Add a Store Named Attribute Geometry node\nStore the result of a field on a geometry as an attribute with the specified name")
DefNode(GeometryNode, GEO_NODE_STORE_NAMED_GRID, 0, StoreNamedGrid, "Store Named Grid", "Add a Store Named Grid node\nStore grid data in a volume geometry with the specified name")
DefNode(GeometryNode, GEO_NODE_STRING_JOIN, 0, StringJoin, "Join Strings", "Add a Join Strings Geometry node\nCombine any number of input strings")
DefNode(GeometryNode, GEO_NODE_STRING_TO_CURVES, def_geo_string_to_curves, StringToCurves, "String to Curves", "Add a String to Curves Geometry node\nGenerate a paragraph of text with a specific font, using a curve instance to store each character")
DefNode(GeometryNode, GEO_NODE_SUBDIVIDE_CURVE, 0, SubdivideCurve, "Subdivide Curve", "Add a Subdivide Curve Geometry node\nDividing each curve segment into a specified number of pieces")
DefNode(GeometryNode, GEO_NODE_SUBDIVIDE_MESH, 0, SubdivideMesh, "Subdivide Mesh", "Add a Subdivide Mesh Geometry node\nDivide mesh faces into smaller ones without changing the shape or volume, using linear interpolation to place the new vertices")
DefNode(GeometryNode, GEO_NODE_SUBDIVISION_SURFACE, 0,SubdivisionSurface, "Subdivision Surface", "Add a Subdivision Surface Geometry node\nDivide mesh faces to form a smooth surface, using the Catmull-Clark subdivision method")
DefNode(GeometryNode, GEO_NODE_SWITCH, 0, Switch, "Switch", "Add a Switch Geometry node\nSwitch between two inputs")
DefNode(GeometryNode, GEO_NODE_TOOL_3D_CURSOR, 0, Tool3DCursor, "3D Cursor", "Add a 3D Cursor Geometry node\nThe scene's 3D cursor location and rotation")
DefNode(GeometryNode, GEO_NODE_TOOL_ACTIVE_ELEMENT, 0, ToolActiveElement, "Active Element", "Add an Active Element node\nActive element indices of the edited geometry, for tool execution")
DefNode(GeometryNode, GEO_NODE_TOOL_FACE_SET, 0, ToolFaceSet, "Face Set", "Add a Face Set Geometry node\nEach face's sculpt face set value")
DefNode(GeometryNode, GEO_NODE_TOOL_MOUSE_POSITION, 0, ToolMousePosition, "Mouse Position", "Add a Mouse Position Geometry node\nRetrieve the position of the mouse cursor")
DefNode(GeometryNode, GEO_NODE_TOOL_SELECTION, 0, ToolSelection, "Selection", "Add a Selection Geometry node\nUser selection of the edited geometry, for tool execution")
DefNode(GeometryNode, GEO_NODE_TOOL_SET_FACE_SET, 0, ToolSetFaceSet, "Set Face Set", "Add a Set Face Set Geometry node\nSet sculpt face set values for faces")
DefNode(GeometryNode, GEO_NODE_TOOL_SET_SELECTION, 0, ToolSetSelection, "Set Selection", "Add a Set Selection Geometry node\nSet selection of the edited geometry, for tool execution")
DefNode(GeometryNode, GEO_NODE_TOOL_VIEWPORT_TRANSFORM, 0, ViewportTransform, "Viewport Transform", "Add a Viewport Transform node\nRetrieve the view direction and location of the 3D viewport")
DefNode(GeometryNode, GEO_NODE_TRANSFORM_GEOMETRY, 0, Transform, "Transform Geometry", "Add a Transform Geometry Geometry node\nTranslate, rotate or scale the geometry")
DefNode(GeometryNode, GEO_NODE_TRANSLATE_INSTANCES, 0,TranslateInstances, "Translate Instances", "Add a Translate Instances Geometry node\nMove top-level geometry instances in local or global space")
DefNode(GeometryNode, GEO_NODE_TRIANGULATE, 0, Triangulate, "Triangulate", "Add a Triangulate Geometry node\nConvert all faces in a mesh to triangular faces")
DefNode(GeometryNode, GEO_NODE_TRIM_CURVE, 0, TrimCurve, "Trim Curve", "Add a Trim Curve Geometry node\nShorten curves by removing portions at the start or end")
DefNode(GeometryNode, GEO_NODE_UV_PACK_ISLANDS, 0, UVPackIslands, "Pack UV Islands", "Add a Pack UV Islands Geometry node\nScale islands of a UV map and move them so they fill the UV space as much as possible")
DefNode(GeometryNode, GEO_NODE_UV_UNWRAP, 0, UVUnwrap, "UV Unwrap", "Add a UV Unwrap Geometry node\nGenerate a UV map based on seam edges")
DefNode(GeometryNode, GEO_NODE_VIEWER, 0, Viewer, "Viewer", "Add a Viewer Geometry node\nDisplay the input data in the Spreadsheet Editor")
DefNode(GeometryNode, GEO_NODE_VOLUME_CUBE, 0, VolumeCube, "Volume Cube", "Add a Volume Cube Geometry node\nGenerate a dense volume with a field that controls the density at each grid voxel based on its position")
DefNode(GeometryNode, GEO_NODE_VOLUME_TO_MESH, 0, VolumeToMesh, "Volume to Mesh", "Add a Volume to Mesh Geometry node\nGenerate a mesh on the \"surface\" of a volume")
DefNode(GeometryNode, GEO_NODE_WARNING, 0, Warning, "Warning", "Add a Warning node\nCreate custom warnings in node groups")

/* undefine macros */
#undef DefNode

    /* clang-format on */
