/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/** \file
 * \ingroup nodes
 */

/* intentionally no include guard */

/* Keep aligned args for readability. */
/* clang-format off */

/* Empty definitions for undefined macros to avoid warnings */
#ifndef DefNode
#define DefNode(Category, ID, DefFunc, EnumName, StructName, UIName, UIDesc)
#endif

/* WARNING! If you edit those strings, please do the same in relevant nodes files (under blender/nodes/...)! */

/*       Tree type       Node ID                  RNA def function        Enum name         Struct name       UI Name              UI Description */
DefNode(Node,           NODE_FRAME,              def_frame,              "FRAME",          Frame,            "Frame",             "Add a frame where you can collect nodes together"              )
DefNode(Node,           NODE_GROUP,              def_group,              "GROUP",          Group,            "Group",             "Create a node group from the selected nodes"              )
DefNode(Node,           NODE_GROUP_INPUT,        def_group_input,        "GROUP_INPUT",    GroupInput,       "Group Input",       "Add a Group Input node"              )
DefNode(Node,           NODE_GROUP_OUTPUT,       def_group_output,       "GROUP_OUTPUT",   GroupOutput,      "Group Output",      "Add a Group Output node"              )
DefNode(Node,           NODE_REROUTE,            0,                      "REROUTE",        Reroute,          "Reroute",           "Add a reroute point that can be used to reroute connections"              )

DefNode(ShaderNode,     SH_NODE_RGB,             0,                      "RGB",            RGB,              "RGB",               "Add a RGB Shader node"              )
DefNode(ShaderNode,     SH_NODE_VALUE,           0,                      "VALUE",          Value,            "Value",             "Add a Value Shader node"              )
DefNode(ShaderNode,     SH_NODE_MIX_RGB,         def_mix_rgb,            "MIX_RGB",        MixRGB,           "MixRGB",            "Add a Mix RGB Shader node"              )
DefNode(ShaderNode,     SH_NODE_VALTORGB,        def_colorramp,          "VALTORGB",       ValToRGB,         "ColorRamp",         "Add a Color Ramp Shader node"              )
DefNode(ShaderNode,     SH_NODE_RGBTOBW,         0,                      "RGBTOBW",        RGBToBW,          "RGB to BW",         "Add a RGB to BW Shader node"              )
DefNode(ShaderNode,     SH_NODE_SHADERTORGB,     0,                      "SHADERTORGB",    ShaderToRGB,      "Shader to RGB",     "Add a Shader to RGB Shader node"              )
DefNode(ShaderNode,     SH_NODE_NORMAL,          0,                      "NORMAL",         Normal,           "Normal",            "Add a Normal Shader node"              )
DefNode(ShaderNode,     SH_NODE_GAMMA,           0,                      "GAMMA",          Gamma,            "Gamma",             "Add a Gamma Shader node"              )
DefNode(ShaderNode,     SH_NODE_BRIGHTCONTRAST,  0,                      "BRIGHTCONTRAST", BrightContrast,   "Bright Contrast",   "Add a Bright Contrast Shader node"              )
DefNode(ShaderNode,     SH_NODE_MAPPING,         def_sh_mapping,         "MAPPING",        Mapping,          "Mapping",           "Add a Mapping Shader node"              )
DefNode(ShaderNode,     SH_NODE_CURVE_VEC,       def_vector_curve,       "CURVE_VEC",      VectorCurve,      "Vector Curves",     "Add a Vector Curves Shader node"              )
DefNode(ShaderNode,     SH_NODE_CURVE_RGB,       def_rgb_curve,          "CURVE_RGB",      RGBCurve,         "RGB Curves",        "Add a RGB Curves Shader node"              )
DefNode(ShaderNode,     SH_NODE_CAMERA,          0,                      "CAMERA",         CameraData,       "Camera Data",       "Add a Camera Data Shader node"              )
DefNode(ShaderNode,     SH_NODE_MAP_RANGE,       def_map_range,          "MAP_RANGE",      MapRange,         "Map Range",         "Add a Map Range Shader node"              )
DefNode(ShaderNode,     SH_NODE_CLAMP,           def_clamp,              "CLAMP",          Clamp,            "Clamp",             "Add a Clamp Shader node"              )
DefNode(ShaderNode,     SH_NODE_MATH,            def_math,               "MATH",           Math,             "Math",              "Add a Math Shader node"              )
DefNode(ShaderNode,     SH_NODE_VECTOR_MATH,     def_vector_math,        "VECT_MATH",      VectorMath,       "Vector Math",       "Add a Vector Math Shader node"              )
DefNode(ShaderNode,     SH_NODE_SQUEEZE,         0,                      "SQUEEZE",        Squeeze,          "Squeeze Value",     "Add a Squeeze Value Shader node"              )
DefNode(ShaderNode,     SH_NODE_INVERT,          0,                      "INVERT",         Invert,           "Invert",            "Add a Invert Shader node"              )
DefNode(ShaderNode,     SH_NODE_SEPRGB,          0,                      "SEPRGB",         SeparateRGB,      "Separate RGB",      "Add a Separate RGB Shader node"              )
DefNode(ShaderNode,     SH_NODE_COMBRGB,         0,                      "COMBRGB",        CombineRGB,       "Combine RGB",       "Add a Combine RGB Shader node"              )
DefNode(ShaderNode,     SH_NODE_HUE_SAT,         0,                      "HUE_SAT",        HueSaturation,    "Hue/Saturation",    "Add a Hue / Saturation Shader node"              )

DefNode(ShaderNode,     SH_NODE_OUTPUT_MATERIAL,    def_sh_output,          "OUTPUT_MATERIAL",    OutputMaterial,   "Material Output",   "Add a Material Output Shader node"       )
DefNode(ShaderNode,     SH_NODE_EEVEE_SPECULAR,     0,                      "EEVEE_SPECULAR",     EeveeSpecular,    "Specular",          "Add a Specular Shader node"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_LIGHT,       def_sh_output,          "OUTPUT_LIGHT",       OutputLight,      "Light Output",      "Add a Light Output Shader node"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_WORLD,       def_sh_output,          "OUTPUT_WORLD",       OutputWorld,      "World Output",      "Add a World Output Shader node"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_LINESTYLE,   def_sh_output_linestyle,"OUTPUT_LINESTYLE",   OutputLineStyle,  "Line Style Output", "Add a Line Style Output Shader node"       )
DefNode(ShaderNode,     SH_NODE_FRESNEL,            0,                      "FRESNEL",            Fresnel,          "Fresnel",           "Add a Fresnel Shader node"       )
DefNode(ShaderNode,     SH_NODE_LAYER_WEIGHT,       0,                      "LAYER_WEIGHT",       LayerWeight,      "Layer Weight",      "Add a Layer Weight Shader node"       )
DefNode(ShaderNode,     SH_NODE_MIX_SHADER,         0,                      "MIX_SHADER",         MixShader,        "Mix Shader",        "Add a Mix Shader Shader node"       )
DefNode(ShaderNode,     SH_NODE_ADD_SHADER,         0,                      "ADD_SHADER",         AddShader,        "Add Shader",        "Add a Add Shader Shader node"       )
DefNode(ShaderNode,     SH_NODE_ATTRIBUTE,          def_sh_attribute,       "ATTRIBUTE",          Attribute,        "Attribute",         "Add a Attribute Shader node"       )
DefNode(ShaderNode,     SH_NODE_AMBIENT_OCCLUSION,  def_sh_ambient_occlusion,"AMBIENT_OCCLUSION", AmbientOcclusion, "Ambient Occlusion", "Add a Ambient Occlusion Shader node"       )
DefNode(ShaderNode,     SH_NODE_BACKGROUND,         0,                      "BACKGROUND",         Background,       "Background",        "Add a Background Shader node"       )
DefNode(ShaderNode,     SH_NODE_HOLDOUT,            0,                      "HOLDOUT",            Holdout,          "Holdout",           "Add a Holdout Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_ANISOTROPIC,   def_anisotropic,        "BSDF_ANISOTROPIC",   BsdfAnisotropic,  "Anisotropic BSDF",  "Add a Anisotropic BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_DIFFUSE,       0,                      "BSDF_DIFFUSE",       BsdfDiffuse,      "Diffuse BSDF",      "Add a Diffuse BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_PRINCIPLED,    def_principled,         "BSDF_PRINCIPLED",    BsdfPrincipled,   "Principled BSDF",   "Add a Principled BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_GLOSSY,        def_glossy,             "BSDF_GLOSSY",        BsdfGlossy,       "Glossy BSDF",       "Add a Glossy BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_GLASS,         def_glass,              "BSDF_GLASS",         BsdfGlass,        "Glass BSDF",        "Add a Glass BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_REFRACTION,    def_refraction,         "BSDF_REFRACTION",    BsdfRefraction,   "Refraction BSDF",   "Add a Refraction BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_TRANSLUCENT,   0,                      "BSDF_TRANSLUCENT",   BsdfTranslucent,  "Translucent BSDF",  "Add a Translucent BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_TRANSPARENT,   0,                      "BSDF_TRANSPARENT",   BsdfTransparent,  "Transparent BSDF",  "Add a Transparent BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_VELVET,        0,                      "BSDF_VELVET",        BsdfVelvet,       "Velvet BSDF",       "Add a Velvet BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_TOON,          def_toon,               "BSDF_TOON",          BsdfToon,         "Toon BSDF",         "Add a Toon BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_HAIR,          def_hair,               "BSDF_HAIR",          BsdfHair,         "Hair BSDF",         "Add a Hair BSDF Shader node"       )
DefNode(ShaderNode,     SH_NODE_BSDF_HAIR_PRINCIPLED,  def_hair_principled, "BSDF_HAIR_PRINCIPLED", BsdfHairPrincipled,  "Principled Hair BSDF", "Add a Principled Hair BSDF Shader node")
DefNode(ShaderNode,     SH_NODE_SUBSURFACE_SCATTERING, def_sh_subsurface,   "SUBSURFACE_SCATTERING",SubsurfaceScattering,"Subsurface Scattering","Add a Subsurface Scattering Shader node")
DefNode(ShaderNode,     SH_NODE_VOLUME_ABSORPTION,  0,                      "VOLUME_ABSORPTION",  VolumeAbsorption, "Volume Absorption", "Add a Volume Absorption Shader node"       )
DefNode(ShaderNode,     SH_NODE_VOLUME_SCATTER,     0,                      "VOLUME_SCATTER",     VolumeScatter,    "Volume Scatter",    "Add a Volume Scatter Shader node"       )
DefNode(ShaderNode,     SH_NODE_VOLUME_PRINCIPLED,  0,                      "PRINCIPLED_VOLUME",  VolumePrincipled, "Principled Volume", "Add a Principled Volume Shader node"       )
DefNode(ShaderNode,     SH_NODE_EMISSION,           0,                      "EMISSION",           Emission,         "Emission",          "Add a Emission Shader node"       )
DefNode(ShaderNode,     SH_NODE_NEW_GEOMETRY,       0,                      "NEW_GEOMETRY",       NewGeometry,      "Geometry",          "Add a Geometry Shader node"       )
DefNode(ShaderNode,     SH_NODE_LIGHT_PATH,         0,                      "LIGHT_PATH",         LightPath,        "Light Path",        "Add a Light Path Shader node"       )
DefNode(ShaderNode,     SH_NODE_LIGHT_FALLOFF,      0,                      "LIGHT_FALLOFF",      LightFalloff,     "Light Falloff",     "Add a Light Falloff Shader node"       )
DefNode(ShaderNode,     SH_NODE_OBJECT_INFO,        0,                      "OBJECT_INFO",        ObjectInfo,       "Object Info",       "Add a Object Info Shader node"       )
DefNode(ShaderNode,     SH_NODE_PARTICLE_INFO,      0,                      "PARTICLE_INFO",      ParticleInfo,     "Particle Info",     "Add a Particle Info Shader node"       )
DefNode(ShaderNode,     SH_NODE_HAIR_INFO,          0,                      "HAIR_INFO",          HairInfo,         "Hair Info",         "Add a Hair Info Shader node"       )
DefNode(ShaderNode,     SH_NODE_VOLUME_INFO,        0,                      "VOLUME_INFO",        VolumeInfo,       "Volume Info",       "Add a Volume Info Shader node"       )
DefNode(ShaderNode,     SH_NODE_WIREFRAME,          def_sh_tex_wireframe,   "WIREFRAME",          Wireframe,        "Wireframe",         "Add a Wireframe Shader node"       )
DefNode(ShaderNode,     SH_NODE_WAVELENGTH,         0,                      "WAVELENGTH",         Wavelength,       "Wavelength",        "Add a Wavelength Shader node"       )
DefNode(ShaderNode,     SH_NODE_BLACKBODY,          0,                      "BLACKBODY",          Blackbody,        "Blackbody",         "Add a Blackbody Shader node"       )
DefNode(ShaderNode,     SH_NODE_BUMP,               def_sh_bump,            "BUMP",               Bump,             "Bump",              "Add a Bump Shader node"       )
DefNode(ShaderNode,     SH_NODE_NORMAL_MAP,         def_sh_normal_map,      "NORMAL_MAP",         NormalMap,        "Normal Map",        "Add a Normal Map Shader node"       )
DefNode(ShaderNode,     SH_NODE_TANGENT,            def_sh_tangent,         "TANGENT",            Tangent,          "Tangent",           "Add a Tangent Shader node"       )
DefNode(ShaderNode,     SH_NODE_SCRIPT,             def_sh_script,          "SCRIPT",             Script,           "Script",            "Add a Script Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_IMAGE,          def_sh_tex_image,       "TEX_IMAGE",          TexImage,         "Image Texture",     "Add a Image Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_ENVIRONMENT,    def_sh_tex_environment, "TEX_ENVIRONMENT",    TexEnvironment,   "Environment Texture","Add a Environment Texture Shader node"      )
DefNode(ShaderNode,     SH_NODE_TEX_SKY,            def_sh_tex_sky,         "TEX_SKY",            TexSky,           "Sky Texture",       "Add a Sky Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_GRADIENT,       def_sh_tex_gradient,    "TEX_GRADIENT",       TexGradient,      "Gradient Texture",  "Add a Gradient Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_NOISE,          def_sh_tex_noise,       "TEX_NOISE",          TexNoise,         "Noise Texture",     "Add a Noise Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_MAGIC,          def_sh_tex_magic,       "TEX_MAGIC",          TexMagic,         "Magic Texture",     "Add a Magic Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_WAVE,           def_sh_tex_wave,        "TEX_WAVE",           TexWave,          "Wave Texture",      "Add a Wave Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_MUSGRAVE,       def_sh_tex_musgrave,    "TEX_MUSGRAVE",       TexMusgrave,      "Musgrave Texture",  "Add a Musgrave Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_VORONOI,        def_sh_tex_voronoi,     "TEX_VORONOI",        TexVoronoi,       "Voronoi Texture",   "Add a Voronoi Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_CHECKER,        def_sh_tex_checker,     "TEX_CHECKER",        TexChecker,       "Checker Texture",   "Add a Checker Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_BRICK,          def_sh_tex_brick,       "TEX_BRICK",          TexBrick,         "Brick Texture",     "Add a Brick Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_POINTDENSITY,   def_sh_tex_pointdensity,"TEX_POINTDENSITY",   TexPointDensity,  "Point Density",     "Add a Point Density Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_COORD,          def_sh_tex_coord,       "TEX_COORD",          TexCoord,         "Texture Coordinate","Add a Texture Coordinate Shader node"       )
DefNode(ShaderNode,     SH_NODE_VECTOR_ROTATE,      def_sh_vector_rotate,   "VECTOR_ROTATE",      VectorRotate,     "Vector Rotate",     "Add a Vector Rotate Shader node"       )
DefNode(ShaderNode,     SH_NODE_VECT_TRANSFORM,     def_sh_vect_transform,  "VECT_TRANSFORM",     VectorTransform,  "Vector Transform",  "Add a Vector Transform Shader node"       )
DefNode(ShaderNode,     SH_NODE_SEPHSV,             0,                      "SEPHSV",             SeparateHSV,      "Separate HSV",      "Add a Separate HSV Shader node"       )
DefNode(ShaderNode,     SH_NODE_COMBHSV,            0,                      "COMBHSV",            CombineHSV,       "Combine HSV",       "Add a Combine HSV Shader node"       )
DefNode(ShaderNode,     SH_NODE_UVMAP,              def_sh_uvmap,           "UVMAP",              UVMap,            "UV Map",            "Add a UV Map Shader node"       )
DefNode(ShaderNode,     SH_NODE_VERTEX_COLOR,       def_sh_vertex_color,    "VERTEX_COLOR",       VertexColor,      "Vertex Color",      "Add a Vertex Color Shader node"       )
DefNode(ShaderNode,     SH_NODE_UVALONGSTROKE,      def_sh_uvalongstroke,   "UVALONGSTROKE",      UVAlongStroke,    "UV Along Stroke",   "Add a UV Along Stroke Shader node"       )
DefNode(ShaderNode,     SH_NODE_SEPXYZ,             0,                      "SEPXYZ",             SeparateXYZ,      "Separate XYZ",      "Add a Separate XYZ Shader node"       )
DefNode(ShaderNode,     SH_NODE_COMBXYZ,            0,                      "COMBXYZ",            CombineXYZ,       "Combine XYZ",       "Add a Combine XYZ Shader node"       )
DefNode(ShaderNode,     SH_NODE_BEVEL,              def_sh_bevel,           "BEVEL",              Bevel,            "Bevel",             "Add a Bevel Shader node"       )
DefNode(ShaderNode,     SH_NODE_DISPLACEMENT,       def_sh_displacement,    "DISPLACEMENT",       Displacement,     "Displacement",      "Add a Displacement Shader node"       )
DefNode(ShaderNode,     SH_NODE_VECTOR_DISPLACEMENT,def_sh_vector_displacement,"VECTOR_DISPLACEMENT",VectorDisplacement,"Vector Displacement","Add a Vector Displacement Shader node"  )
DefNode(ShaderNode,     SH_NODE_TEX_IES,            def_sh_tex_ies,         "TEX_IES",            TexIES,           "IES Texture",       "Add a IES Texture Shader node"       )
DefNode(ShaderNode,     SH_NODE_TEX_WHITE_NOISE,    def_sh_tex_white_noise, "TEX_WHITE_NOISE",    TexWhiteNoise,    "White Noise",       "Add a White Noise Shader node"       )
DefNode(ShaderNode,     SH_NODE_OUTPUT_AOV,         def_sh_output_aov,      "OUTPUT_AOV",         OutputAOV,        "AOV Output",        "Add a AOV Output Shader node"       )

DefNode(CompositorNode, CMP_NODE_VIEWER,         def_cmp_viewer,         "VIEWER",         Viewer,           "Viewer",            "Add a Viewer Compositor node"              )
DefNode(CompositorNode, CMP_NODE_RGB,            0,                      "RGB",            RGB,              "RGB",               "Add a RGB Compositor node"              )
DefNode(CompositorNode, CMP_NODE_VALUE,          0,                      "VALUE",          Value,            "Value",             "Add a Value Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MIX_RGB,        def_mix_rgb,            "MIX_RGB",        MixRGB,           "Mix",               "Add a Mix Compositor node"              )
DefNode(CompositorNode, CMP_NODE_VALTORGB,       def_colorramp,          "VALTORGB",       ValToRGB,         "ColorRamp",         "Add a ColorRamp Compositor node"              )
DefNode(CompositorNode, CMP_NODE_RGBTOBW,        0,                      "RGBTOBW",        RGBToBW,          "RGB to BW",         "Add a RGB to BW Compositor node"              )
DefNode(CompositorNode, CMP_NODE_NORMAL,         0,                      "NORMAL",         Normal,           "Normal",            "Add a Normal Compositor node"              )
DefNode(CompositorNode, CMP_NODE_CURVE_VEC,      def_vector_curve,       "CURVE_VEC",      CurveVec,         "Vector Curves",     "Add a Vector Curves Compositor node"              )
DefNode(CompositorNode, CMP_NODE_CURVE_RGB,      def_rgb_curve,          "CURVE_RGB",      CurveRGB,         "RGB Curves",        "Add a RGB Curves Compositor node"              )
DefNode(CompositorNode, CMP_NODE_ALPHAOVER,      def_cmp_alpha_over,     "ALPHAOVER",      AlphaOver,        "Alpha Over",        "Add a Alpha Over Compositor node"              )
DefNode(CompositorNode, CMP_NODE_BLUR,           def_cmp_blur,           "BLUR",           Blur,             "Blur",              "Add a Blur Compositor node"              )
DefNode(CompositorNode, CMP_NODE_FILTER,         def_cmp_filter,         "FILTER",         Filter,           "Filter",            "Add a Filter Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MAP_VALUE,      def_cmp_map_value,      "MAP_VALUE",      MapValue,         "Map Value",         "Add a Map Value Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MAP_RANGE,      def_cmp_map_range,      "MAP_RANGE",      MapRange,         "Map Range",         "Add a Map Range Compositor node"              )
DefNode(CompositorNode, CMP_NODE_TIME,           def_time,               "TIME",           Time,             "Time",              "Add a Time Compositor node"              )
DefNode(CompositorNode, CMP_NODE_VECBLUR,        def_cmp_vector_blur,    "VECBLUR",        VecBlur,          "Vector Blur",       "Add a Vector Blur Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SEPRGBA,        0,                      "SEPRGBA",        SepRGBA,          "Separate RGBA",     "Add a Separate RGBA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SEPHSVA,        0,                      "SEPHSVA",        SepHSVA,          "Separate HSVA",     "Add a Separate HSVA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SETALPHA,       def_cmp_set_alpha,      "SETALPHA",       SetAlpha,         "Set Alpha",         "Add a Set Alpha Compositor node"              )
DefNode(CompositorNode, CMP_NODE_HUE_SAT,        0,                      "HUE_SAT",        HueSat,           "Hue Saturation Value","Add a Hue Saturation Value Compositor node"            )
DefNode(CompositorNode, CMP_NODE_IMAGE,          def_cmp_image,          "IMAGE",          Image,            "Image",             "Add a Image Compositor node"              )
DefNode(CompositorNode, CMP_NODE_R_LAYERS,       def_cmp_render_layers,  "R_LAYERS",       RLayers,          "Render Layers",     "Add a Render Layers Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COMPOSITE,      def_cmp_composite,      "COMPOSITE",      Composite,        "Composite",         "Add a Composite Compositor node"              )
/* NB: OutputFile node has special rna setup function called in rna_nodetree.c */
DefNode(CompositorNode, CMP_NODE_OUTPUT_FILE,    0,                      "OUTPUT_FILE",    OutputFile,       "File Output",       "Add a File Output Compositor node"              )
DefNode(CompositorNode, CMP_NODE_TEXTURE,        def_texture,            "TEXTURE",        Texture,          "Texture",           "Add a Texture Compositor node"              )
DefNode(CompositorNode, CMP_NODE_TRANSLATE,      def_cmp_translate,      "TRANSLATE",      Translate,        "Translate",         "Add a Translate Compositor node"              )
DefNode(CompositorNode, CMP_NODE_ZCOMBINE,       def_cmp_zcombine,       "ZCOMBINE",       Zcombine,         "Z Combine",         "Add a Z Combine Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COMBRGBA,       0,                      "COMBRGBA",       CombRGBA,         "Combine RGBA",      "Add a Combine RGBA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DILATEERODE,    def_cmp_dilate_erode,   "DILATEERODE",    DilateErode,      "Dilate/Erode",      "Add a Dilate/Erode Compositor node"              )
DefNode(CompositorNode, CMP_NODE_INPAINT,        def_cmp_inpaint,        "INPAINT",        Inpaint,          "Inpaint",           "Add a Inpaint Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DESPECKLE,      def_cmp_despeckle,      "DESPECKLE",      Despeckle,        "Despeckle",         "Add a Despeckle Compositor node"              )
DefNode(CompositorNode, CMP_NODE_ROTATE,         def_cmp_rotate,         "ROTATE",         Rotate,           "Rotate",            "Add a Rotate Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SCALE,          def_cmp_scale,          "SCALE",          Scale,            "Scale",             "Add a Scale Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SEPYCCA,        def_cmp_ycc,            "SEPYCCA",        SepYCCA,          "Separate YCbCrA",   "Add a Separate YCbCrA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COMBYCCA,       def_cmp_ycc,            "COMBYCCA",       CombYCCA,         "Combine YCbCrA",    "Add a Combine YCbCrA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SEPYUVA,        0,                      "SEPYUVA",        SepYUVA,          "Separate YUVA",     "Add a Separate YUVA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COMBYUVA,       0,                      "COMBYUVA",       CombYUVA,         "Combine YUVA",      "Add a Combine YUVA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DIFF_MATTE,     def_cmp_diff_matte,     "DIFF_MATTE",     DiffMatte,        "Difference Key",    "Add a Difference Key Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COLOR_SPILL,    def_cmp_color_spill,    "COLOR_SPILL",    ColorSpill,       "Color Spill",       "Add a Color Spill Compositor node"              )
DefNode(CompositorNode, CMP_NODE_CHROMA_MATTE,   def_cmp_chroma_matte,   "CHROMA_MATTE",   ChromaMatte,      "Chroma Key",        "Add a Chroma Key Compositor node"              )
DefNode(CompositorNode, CMP_NODE_CHANNEL_MATTE,  def_cmp_channel_matte,  "CHANNEL_MATTE",  ChannelMatte,     "Channel Key",       "Add a Channel Key Compositor node"              )
DefNode(CompositorNode, CMP_NODE_FLIP,           def_cmp_flip,           "FLIP",           Flip,             "Flip",              "Add a Flip Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SPLITVIEWER,    def_cmp_splitviewer,    "SPLITVIEWER",    SplitViewer,      "Split Viewer",      "Add a Split Viewer Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MAP_UV,         def_cmp_map_uv,         "MAP_UV",         MapUV,            "Map UV",            "Add a Map UV Compositor node"              )
DefNode(CompositorNode, CMP_NODE_ID_MASK,        def_cmp_id_mask,        "ID_MASK",        IDMask,           "ID Mask",           "Add a ID Mask Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DOUBLEEDGEMASK, def_cmp_double_edge_mask,"DOUBLEEDGEMASK", DoubleEdgeMask,  "Double Edge Mask",  "Add a Double Edge Mask Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DEFOCUS,        def_cmp_defocus,        "DEFOCUS",        Defocus,          "Defocus",           "Add a Defocus Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DISPLACE,       0,                      "DISPLACE",       Displace,         "Displace",          "Add a Displace Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COMBHSVA,       0,                      "COMBHSVA",       CombHSVA,         "Combine HSVA",      "Add a Combine HSVA Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MATH,           def_math,               "MATH",           Math,             "Math",              "Add a Math Compositor node"              )
DefNode(CompositorNode, CMP_NODE_LUMA_MATTE,     def_cmp_luma_matte,     "LUMA_MATTE",     LumaMatte,        "Luminance Key",     "Add a Luminance Key Compositor node"              )
DefNode(CompositorNode, CMP_NODE_BRIGHTCONTRAST, def_cmp_brightcontrast, "BRIGHTCONTRAST", BrightContrast,   "Bright/Contrast",   "Add a Bright/Contrast Compositor node"              )
DefNode(CompositorNode, CMP_NODE_GAMMA,          0,                      "GAMMA",          Gamma,            "Gamma",             "Add a Gamma Compositor node"              )
DefNode(CompositorNode, CMP_NODE_INVERT,         def_cmp_invert,         "INVERT",         Invert,           "Invert",            "Add a Invert Compositor node"              )
DefNode(CompositorNode, CMP_NODE_NORMALIZE,      0,                      "NORMALIZE",      Normalize,        "Normalize",         "Add a Normalize Compositor node"              )
DefNode(CompositorNode, CMP_NODE_CROP,           def_cmp_crop,           "CROP",           Crop,             "Crop",              "Add a Crop Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DBLUR,          def_cmp_dblur,          "DBLUR",          DBlur,            "Directional Blur",  "Add a Directional Blur Compositor node"              )
DefNode(CompositorNode, CMP_NODE_BILATERALBLUR,  def_cmp_bilateral_blur, "BILATERALBLUR",  Bilateralblur,    "Bilateral Blur",    "Add a Bilateral Blur Compositor node"              )
DefNode(CompositorNode, CMP_NODE_PREMULKEY,      def_cmp_premul_key,     "PREMULKEY",      PremulKey,        "Alpha Convert",     "Add a Alpha Convert Compositor node"              )
DefNode(CompositorNode, CMP_NODE_GLARE,          def_cmp_glare,          "GLARE",          Glare,            "Glare",             "Add a Glare Compositor node"              )
DefNode(CompositorNode, CMP_NODE_TONEMAP,        def_cmp_tonemap,        "TONEMAP",        Tonemap,          "Tonemap",           "Add a Tonemap Compositor node"              )
DefNode(CompositorNode, CMP_NODE_LENSDIST,       def_cmp_lensdist,       "LENSDIST",       Lensdist,         "Lens Distortion",   "Add a Lens Distortion Compositor node"              )
DefNode(CompositorNode, CMP_NODE_VIEW_LEVELS,    def_cmp_levels,         "LEVELS",         Levels,           "Levels",            "Add a Levels Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COLOR_MATTE,    def_cmp_color_matte,    "COLOR_MATTE",    ColorMatte,       "Color Key",         "Add a Color Key Compositor node"              )
DefNode(CompositorNode, CMP_NODE_DIST_MATTE,     def_cmp_distance_matte, "DISTANCE_MATTE", DistanceMatte,    "Distance Key",      "Add a Distance Key Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COLORBALANCE,   def_cmp_colorbalance,   "COLORBALANCE",   ColorBalance,     "Color Balance",     "Add a Color Balance Compositor node"              )
DefNode(CompositorNode, CMP_NODE_HUECORRECT,     def_cmp_huecorrect,     "HUECORRECT",     HueCorrect,       "Hue Correct",       "Add a Hue Correct Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MOVIECLIP,      def_cmp_movieclip,      "MOVIECLIP",      MovieClip,        "Movie Clip",        "Add a Movie Clip Compositor node"              )
DefNode(CompositorNode, CMP_NODE_TRANSFORM,      dev_cmd_transform,      "TRANSFORM",      Transform,        "Transform",         "Add a Transform Compositor node"              )
DefNode(CompositorNode, CMP_NODE_STABILIZE2D,    def_cmp_stabilize2d,    "STABILIZE2D",    Stabilize,        "Stabilize 2D",      "Add a Stabilize 2D Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MOVIEDISTORTION,def_cmp_moviedistortion,"MOVIEDISTORTION",MovieDistortion,  "Movie Distortion",  "Add a Movie Distortion Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MASK_BOX,       def_cmp_boxmask,        "BOXMASK",        BoxMask,          "Box Mask",          "Add a Box Mask Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MASK_ELLIPSE,   def_cmp_ellipsemask,    "ELLIPSEMASK",    EllipseMask,      "Ellipse Mask",      "Add a Ellipse Mask Compositor node"              )
DefNode(CompositorNode, CMP_NODE_BOKEHIMAGE,     def_cmp_bokehimage,     "BOKEHIMAGE",     BokehImage,       "Bokeh Image",       "Add a Bokeh Image Compositor node"              )
DefNode(CompositorNode, CMP_NODE_BOKEHBLUR,      def_cmp_bokehblur,      "BOKEHBLUR",      BokehBlur,        "Bokeh Blur",        "Add a Bokeh Blur Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SWITCH,         def_cmp_switch,         "SWITCH",         Switch,           "Switch",            "Add a Switch Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SWITCH_VIEW,    def_cmp_switch_view,    "VIEWSWITCH",     SwitchView,       "View Switch",       "Add a View Switch Compositor node"              )
DefNode(CompositorNode, CMP_NODE_COLORCORRECTION,def_cmp_colorcorrection,"COLORCORRECTION",ColorCorrection,  "Color Correction",  "Add a Color Correction Compositor node"              )
DefNode(CompositorNode, CMP_NODE_MASK,           def_cmp_mask,           "MASK",           Mask,             "Mask",              "Add a Mask Compositor node"              )
DefNode(CompositorNode, CMP_NODE_KEYINGSCREEN,   def_cmp_keyingscreen,   "KEYINGSCREEN",   KeyingScreen,     "Keying Screen",     "Add a Keying Screen Compositor node"              )
DefNode(CompositorNode, CMP_NODE_KEYING,         def_cmp_keying,         "KEYING",         Keying,           "Keying",            "Add a Keying Compositor node"              )
DefNode(CompositorNode, CMP_NODE_TRACKPOS,       def_cmp_trackpos,       "TRACKPOS",       TrackPos,         "Track Position",    "Add a Track Position Compositor node"              )
DefNode(CompositorNode, CMP_NODE_PIXELATE,       0,                      "PIXELATE",       Pixelate,         "Pixelate",          "Add a Pixelate Compositor node"              )
DefNode(CompositorNode, CMP_NODE_PLANETRACKDEFORM,def_cmp_planetrackdeform,"PLANETRACKDEFORM",PlaneTrackDeform,"Plane Track Deform","Add a Plane Track Deform Compositor node"            )
DefNode(CompositorNode, CMP_NODE_CORNERPIN,      0,                      "CORNERPIN",      CornerPin,        "Corner Pin",        "Add a Corner Pin Compositor node"              )
DefNode(CompositorNode, CMP_NODE_SUNBEAMS,       def_cmp_sunbeams,       "SUNBEAMS",       SunBeams,         "Sun Beams",         "Add a Sun Beams Compositor node"              )
DefNode(CompositorNode, CMP_NODE_CRYPTOMATTE,    def_cmp_cryptomatte,    "CRYPTOMATTE_V2", CryptomatteV2,    "Cryptomatte",       "Add a Cryptomatte Compositor node"              )
DefNode(CompositorNode, CMP_NODE_CRYPTOMATTE_LEGACY, def_cmp_cryptomatte_legacy, "CRYPTOMATTE", Cryptomatte, "Cryptomatte (Legacy)", "Add a Cryptomatte (Legacy) Compositor node"           )
DefNode(CompositorNode, CMP_NODE_DENOISE,        def_cmp_denoise,        "DENOISE",        Denoise,          "Denoise",           "Add a Denoise Compositor node"              )
DefNode(CompositorNode, CMP_NODE_EXPOSURE,       0,                      "EXPOSURE",       Exposure,         "Exposure",          "Add a Exposure Compositor node"              )
DefNode(CompositorNode, CMP_NODE_ANTIALIASING,   def_cmp_antialiasing,   "ANTIALIASING",   AntiAliasing,     "Anti-Aliasing",     "Add a Anti-Aliasing Compositor node"              )

DefNode(TextureNode,    TEX_NODE_OUTPUT,         def_tex_output,         "OUTPUT",         Output,           "Output",            "Add a Output Texture node"              )
DefNode(TextureNode,    TEX_NODE_CHECKER,        0,                      "CHECKER",        Checker,          "Checker",           "Add a Checker Texture node"              )
DefNode(TextureNode,    TEX_NODE_TEXTURE,        def_texture,            "TEXTURE",        Texture,          "Texture",           "Add a Texture Texture node"              )
DefNode(TextureNode,    TEX_NODE_BRICKS,         def_tex_bricks,         "BRICKS",         Bricks,           "Bricks",            "Add a Bricks Texture node"              )
DefNode(TextureNode,    TEX_NODE_MATH,           def_math,               "MATH",           Math,             "Math",              "Add a Math Texture node"              )
DefNode(TextureNode,    TEX_NODE_MIX_RGB,        def_mix_rgb,            "MIX_RGB",        MixRGB,           "Mix RGB",           "Add a Mix RGB Texture node"              )
DefNode(TextureNode,    TEX_NODE_RGBTOBW,        0,                      "RGBTOBW",        RGBToBW,          "RGB to BW",         "Add a RGB to BW Texture node"              )
DefNode(TextureNode,    TEX_NODE_VALTORGB,       def_colorramp,          "VALTORGB",       ValToRGB,         "ColorRamp",         "Add a ColorRamp Texture node"              )
DefNode(TextureNode,    TEX_NODE_IMAGE,          def_tex_image,          "IMAGE",          Image,            "Image",             "Add a Image Texture node"              )
DefNode(TextureNode,    TEX_NODE_CURVE_RGB,      def_rgb_curve,          "CURVE_RGB",      CurveRGB,         "RGB Curves",        "Add a RGB Curves Texture node"              )
DefNode(TextureNode,    TEX_NODE_INVERT,         0,                      "INVERT",         Invert,           "Invert",            "Add a Invert Texture node"              )
DefNode(TextureNode,    TEX_NODE_HUE_SAT,        0,                      "HUE_SAT",        HueSaturation,    "Hue/Saturation",    "Add a Hue/Saturation Texture node"              )
DefNode(TextureNode,    TEX_NODE_CURVE_TIME,     def_time,               "CURVE_TIME",     CurveTime,        "Curve Time",        "Add a Curve Time Texture node"              )
DefNode(TextureNode,    TEX_NODE_ROTATE,         0,                      "ROTATE",         Rotate,           "Rotate",            "Add a Rotate Texture node"              )
DefNode(TextureNode,    TEX_NODE_VIEWER,         0,                      "VIEWER",         Viewer,           "Viewer",            "Add a Viewer Texture node"              )
DefNode(TextureNode,    TEX_NODE_TRANSLATE,      0,                      "TRANSLATE",      Translate,        "Translate",         "Add a Translate Texture node"              )
DefNode(TextureNode,    TEX_NODE_COORD,          0,                      "COORD",          Coordinates,      "Coordinates",       "Add a Coordinates Texture node"              )
DefNode(TextureNode,    TEX_NODE_DISTANCE,       0,                      "DISTANCE",       Distance,         "Distance",          "Add a Distance Texture node"              )
DefNode(TextureNode,    TEX_NODE_COMPOSE,        0,                      "COMPOSE",        Compose,          "Combine RGBA",      "Add a Combine RGBA Texture node"              )
DefNode(TextureNode,    TEX_NODE_DECOMPOSE,      0,                      "DECOMPOSE",      Decompose,        "Separate RGBA",     "Add a Separate RGBA Texture node"              )
DefNode(TextureNode,    TEX_NODE_VALTONOR,       0,                      "VALTONOR",       ValToNor,         "Value to Normal",   "Add a Value to Normal Texture node"              )
DefNode(TextureNode,    TEX_NODE_SCALE,          0,                      "SCALE",          Scale,            "Scale",             "Add a Scale Texture node"              )
DefNode(TextureNode,    TEX_NODE_AT,             0,                      "AT",             At,               "At",                "Add a At Texture node"              )
/* procedural textures */
DefNode(TextureNode,    TEX_NODE_PROC+TEX_VORONOI, 0,                    "TEX_VORONOI",    TexVoronoi,       "Voronoi",           "Add a Voronoi Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_BLEND, 0,                      "TEX_BLEND",      TexBlend,         "Blend",             "Add a Blend Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_MAGIC, 0,                      "TEX_MAGIC",      TexMagic,         "Magic",             "Add a Magic Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_MARBLE, 0,                     "TEX_MARBLE",     TexMarble,        "Marble",            "Add a Marble Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_CLOUDS, 0,                     "TEX_CLOUDS",     TexClouds,        "Clouds",            "Add a Clouds Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_WOOD, 0,                       "TEX_WOOD",       TexWood,          "Wood",              "Add a Wood Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_MUSGRAVE, 0,                   "TEX_MUSGRAVE",   TexMusgrave,      "Musgrave",          "Add a Musgrave Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_NOISE, 0,                      "TEX_NOISE",      TexNoise,         "Noise",             "Add a Noise Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_STUCCI, 0,                     "TEX_STUCCI",     TexStucci,        "Stucci",            "Add a Stucci Texture node"              )
DefNode(TextureNode,    TEX_NODE_PROC+TEX_DISTNOISE, 0,                  "TEX_DISTNOISE",  TexDistNoise,     "Distorted Noise",   "Add a Distorted Noise Texture node"              )

DefNode(FunctionNode, FN_NODE_BOOLEAN_MATH,  def_boolean_math,          "BOOLEAN_MATH",     BooleanMath,      "Boolean Math",     "Add a Boolean Math Function node")
DefNode(FunctionNode, FN_NODE_FLOAT_COMPARE, def_float_compare,         "FLOAT_COMPARE",    FloatCompare,     "Float Compare",    "Add a Float Compare Function node")
DefNode(FunctionNode, FN_NODE_INPUT_STRING, def_fn_input_string,        "INPUT_STRING",     InputString,      "String",           "Add a String Function node")
DefNode(FunctionNode, FN_NODE_INPUT_VECTOR, def_fn_input_vector,        "INPUT_VECTOR",     InputVector,      "Vector",           "Add a Vector Function node")
DefNode(FunctionNode, FN_NODE_RANDOM_FLOAT, 0,                          "RANDOM_FLOAT",     RandomFloat,      "Random Float",     "Add a Random Float Function node")

DefNode(GeometryNode, GEO_NODE_ALIGN_ROTATION_TO_VECTOR, def_geo_align_rotation_to_vector,  "ALIGN_ROTATION_TO_VECTOR", AlignRotationToVector, "Align Rotation to Vector",  "Add a Align Rotation to Vector Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_CLAMP, def_geo_attribute_clamp,                    "ATTRIBUTE_CLAMP", AttributeClamp, "Attribute Clamp",                           "Add a Attribute Clamp Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_COLOR_RAMP, def_geo_attribute_color_ramp,          "ATTRIBUTE_COLOR_RAMP", AttributeColorRamp, "Attribute Color Ramp",             "Add a Attribute Color Ramp Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_COMBINE_XYZ, def_geo_attribute_combine_xyz,        "ATTRIBUTE_COMBINE_XYZ", AttributeCombineXYZ, "Attribute Combine XYZ",          "Add a Attribute Combine XYZ Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_COMPARE, def_geo_attribute_attribute_compare,      "ATTRIBUTE_COMPARE", AttributeCompare, "Attribute Compare",                     "Add a Attribute Compare Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_CONVERT, def_geo_attribute_convert,                "ATTRIBUTE_CONVERT", AttributeConvert, "Attribute Convert",                     "Add a Attribute Convert Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_CURVE_MAP, def_geo_attribute_curve_map,            "ATTRIBUTE_CURVE_MAP", AttributeCurveMap, "Attribute Curve Map",                "Add a Attribute Curve Map Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_FILL, def_geo_attribute_fill,                      "ATTRIBUTE_FILL", AttributeFill, "Attribute Fill",                              "Add a Attribute Fill Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_MAP_RANGE, def_geo_attribute_map_range,            "ATTRIBUTE_MAP_RANGE", AttributeMapRange, "Attribute Map Range",                "Add a Attribute Map Range Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_MATH, def_geo_attribute_math,                      "ATTRIBUTE_MATH", AttributeMath, "Attribute Math",                              "Add a Attribute Math Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_MIX, def_geo_attribute_mix,                        "ATTRIBUTE_MIX", AttributeMix, "Attribute Mix",                                 "Add a Attribute Mix Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_PROXIMITY, def_geo_attribute_proximity,            "ATTRIBUTE_PROXIMITY", AttributeProximity, "Attribute Proximity",               "Add a Attribute Proximity Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_RANDOMIZE, def_geo_attribute_randomize,            "ATTRIBUTE_RANDOMIZE", AttributeRandomize, "Attribute Randomize",               "Add a Attribute Randomize Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_REMOVE, 0,                                         "ATTRIBUTE_REMOVE", AttributeRemove, "Attribute Remove",                        "Add a Attribute Remove Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_SAMPLE_TEXTURE, 0,                                 "ATTRIBUTE_SAMPLE_TEXTURE", AttributeSampleTexture, "Attribute Sample Texture", "Add a Attribute Sample Texture Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_SEPARATE_XYZ, def_geo_attribute_separate_xyz,      "ATTRIBUTE_SEPARATE_XYZ", AttributeSeparateXYZ, "Attribute Separate XYZ",       "Add a Attribute Separate XYZ Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_TRANSFER, def_geo_attribute_transfer,              "ATTRIBUTE_TRANSFER", AttributeTransfer, "Attribute Transfer",                  "Add a Attribute Transfer Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_VECTOR_MATH, def_geo_attribute_vector_math,        "ATTRIBUTE_VECTOR_MATH", AttributeVectorMath, "Attribute Vector Math",          "Add a Attribute Vector Math Geometry node")
DefNode(GeometryNode, GEO_NODE_ATTRIBUTE_VECTOR_ROTATE, def_geo_attribute_vector_rotate,    "ATTRIBUTE_VECTOR_ROTATE", AttributeVectorRotate, "Attribute Vector Rotate",    "Add a Attribute Vector Rotate Geometry node")
DefNode(GeometryNode, GEO_NODE_BOOLEAN, def_geo_boolean,                                    "BOOLEAN", Boolean, "Boolean",                                                  "Add a Boolean Geometry node")
DefNode(GeometryNode, GEO_NODE_BOUNDING_BOX, 0,                                             "BOUNDING_BOX", BoundBox, "Bounding Box",                                       "Add a Bounding Box Geometry node")
DefNode(GeometryNode, GEO_NODE_COLLECTION_INFO, def_geo_collection_info,                    "COLLECTION_INFO", CollectionInfo, "Collection Info",                           "Add a Collection Info Geometry node")
DefNode(GeometryNode, GEO_NODE_CONVEX_HULL, 0,                                              "CONVEX_HULL", ConvexHull, "Convex Hull",                                       "Add a Convex Hull Geometry node")
DefNode(GeometryNode, GEO_NODE_CURVE_LENGTH, 0,                                             "CURVE_LENGTH", CurveLength, "Curve Length",                                    "Add a Curve Length Geometry node")
DefNode(GeometryNode, GEO_NODE_CURVE_RESAMPLE, def_geo_curve_resample,                      "CURVE_RESAMPLE", CurveResample, "Resample Curve",                              "Add a Resample Curve Geometry node")
DefNode(GeometryNode, GEO_NODE_CURVE_TO_MESH, 0,                                            "CURVE_TO_MESH", CurveToMesh, "Curve to Mesh",                                  "Add a Curve to Mesh Geometry node")
DefNode(GeometryNode, GEO_NODE_DELETE_GEOMETRY, 0,                                          "DELETE_GEOMETRY", DeleteGeometry, "Delete Geometry",                           "Add a Delete Geometry Geometry node")
DefNode(GeometryNode, GEO_NODE_EDGE_SPLIT, 0,                                               "EDGE_SPLIT", EdgeSplit, "Edge Split",                                          "Add a Edge Split Geometry node")
DefNode(GeometryNode, GEO_NODE_INPUT_MATERIAL, def_geo_input_material,                      "INPUT_MATERIAL", InputMaterial, "Material",                                    "Add a Material Geometry node")
DefNode(GeometryNode, GEO_NODE_IS_VIEWPORT, 0,                                              "IS_VIEWPORT", IsViewport, "Is Viewport",                                       "Add a Is Viewport Geometry node")
DefNode(GeometryNode, GEO_NODE_JOIN_GEOMETRY, 0,                                            "JOIN_GEOMETRY", JoinGeometry, "Join Geometry",                                 "Add a Join Geometry Geometry node")
DefNode(GeometryNode, GEO_NODE_MATERIAL_ASSIGN, 0,                                          "MATERIAL_ASSIGN", MaterialAssign, "Material Assign",                           "Add a Material Assign Geometry node")
DefNode(GeometryNode, GEO_NODE_MATERIAL_REPLACE, 0,                                         "MATERIAL_REPLACE", MaterialReplace, "Material Replace",                        "Add a Material Replace Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CIRCLE, def_geo_mesh_circle,                  "MESH_PRIMITIVE_CIRCLE", MeshCircle, "Circle",                                  "Add a Circle Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CONE, def_geo_mesh_cone,                      "MESH_PRIMITIVE_CONE", MeshCone, "Cone",                                        "Add a Cone Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CUBE, 0,                                      "MESH_PRIMITIVE_CUBE", MeshCube, "Cube",                                        "Add a Cube Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_CYLINDER, def_geo_mesh_cylinder,              "MESH_PRIMITIVE_CYLINDER", MeshCylinder, "Cylinder",                            "Add a Cylinder Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_GRID, 0,                                      "MESH_PRIMITIVE_GRID", MeshGrid, "Grid",                                        "Add a Grid Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_ICO_SPHERE, 0,                                "MESH_PRIMITIVE_ICO_SPHERE", MeshIcoSphere, "Ico Sphere",                       "Add a Ico Sphere Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_LINE, def_geo_mesh_line,                      "MESH_PRIMITIVE_LINE", MeshLine, "Line",                                        "Add a Line Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_PRIMITIVE_UV_SPHERE, 0,                                 "MESH_PRIMITIVE_UV_SPHERE", MeshUVSphere, "UV Sphere",                          "Add a UV Sphere Geometry node")
DefNode(GeometryNode, GEO_NODE_MESH_TO_CURVE, 0,                                            "MESH_TO_CURVE", MeshToCurve, "Mesh to Curve",                                  "Add a Mesh to Curve Geometry node")
DefNode(GeometryNode, GEO_NODE_OBJECT_INFO, def_geo_object_info,                            "OBJECT_INFO", ObjectInfo, "Object Info",                                       "Add a Object Info Geometry node")
DefNode(GeometryNode, GEO_NODE_POINT_DISTRIBUTE, def_geo_point_distribute,                  "POINT_DISTRIBUTE", PointDistribute, "Point Distribute",                        "Add a Point Distribute Geometry node")
DefNode(GeometryNode, GEO_NODE_POINT_INSTANCE, def_geo_point_instance,                      "POINT_INSTANCE", PointInstance, "Point Instance",                              "Add a Point Instance Geometry node")
DefNode(GeometryNode, GEO_NODE_POINT_ROTATE, def_geo_point_rotate,                          "POINT_ROTATE", RotatePoints, "Point Rotate",                                   "Add a Point Rotate Geometry node")
DefNode(GeometryNode, GEO_NODE_POINT_SCALE, def_geo_point_scale,                            "POINT_SCALE", PointScale, "Point Scale",                                       "Add a Point Scale Geometry node")
DefNode(GeometryNode, GEO_NODE_POINT_SEPARATE, 0,                                           "POINT_SEPARATE", PointSeparate, "Point Separate",                              "Add a Point Separate Geometry node")
DefNode(GeometryNode, GEO_NODE_POINT_TRANSLATE, def_geo_point_translate,                    "POINT_TRANSLATE", PointTranslate, "Point Translate",                           "Add a Point Translate Geometry node")
DefNode(GeometryNode, GEO_NODE_POINTS_TO_VOLUME, def_geo_points_to_volume,                  "POINTS_TO_VOLUME", PointsToVolume, "Points to Volume",                         "Add a Points to Volume Geometry node")
DefNode(GeometryNode, GEO_NODE_SELECT_BY_MATERIAL, 0,                                       "SELECT_BY_MATERIAL", SelectByMaterial, "Select by Material",                   "Add a Select by Material Geometry node")
DefNode(GeometryNode, GEO_NODE_SUBDIVIDE, 0,                                                "SUBDIVIDE", Subdivide, "Subdivide",                                            "Add a Subdivide Geometry node")
DefNode(GeometryNode, GEO_NODE_SUBDIVISION_SURFACE, 0,                                      "SUBDIVISION_SURFACE", SubdivisionSurface, "Subdivision Surface",               "Add a Subdivision Surface Geometry node")
DefNode(GeometryNode, GEO_NODE_SWITCH, def_geo_switch,                                      "SWITCH", Switch, "Switch",                                                     "Add a Switch Geometry node")
DefNode(GeometryNode, GEO_NODE_TRANSFORM, 0,                                                "TRANSFORM", Transform, "Transform",                                            "Add a Transform Geometry node")
DefNode(GeometryNode, GEO_NODE_TRIANGULATE, def_geo_triangulate,                            "TRIANGULATE", Triangulate, "Triangulate",                                      "Add a Triangulate Geometry node")
DefNode(GeometryNode, GEO_NODE_VOLUME_TO_MESH, def_geo_volume_to_mesh,                      "VOLUME_TO_MESH", VolumeToMesh, "Volume to Mesh",                               "Add a Volume to Mesh Geometry node")

/* undefine macros */
#undef DefNode

    /* clang-format on */
