# Example
schema_version = "1.0.0"

id = "my_example_package"
name = "Test Package"
tagline = "Single line description"
type = "add-on"
tags = ["UV", "Modeling"]
version = "0.2.0"
blender_version_min = "2.80.0"
maintainer = "Maintainer Name"
license = [
    "SPDX:CC-0",
]
copyright = [
    "2020-2024 Developer Name",
]

[permissions]
network = "Need to sync data to server"
files = "Import/export files from/to disk"
clipboard = "Copy rotations"
camera = "Reason for connecting to a camera"
microphone = "An add-on could do this in theory"

[build]
paths_exclude_pattern = [
    # Exclude all Python cache.
    "__pycache__/",
    # Exclude `.git` and similar.
    ".*",
]
