schema_version = "1.0.0"
id = "is_key_free"
name = "Is key Free"
version = "1.1.3"
tagline = "Find free shortcuts, inform about used and print a key list"
maintainer = "Community"
type = "add-on"
tags = ["Development"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/development_iskeyfree"
copyright = ["2024 Antonio Vazquez (antonioya)"]
