#
# Buildbot only configs
#
buildbot:
    gcc:
        version: '11.0.0'
    cuda10:
        version: '10.1.243'
    cuda11:
        version: '11.4.1'
    hip:
        version: '5.3.22480'
    optix:
        version: '7.3.0'
    ocloc:
        version: '101.4032'
    cmake:
        default:
            version: any
            overrides: {}
        darwin-arm64:
            overrides: {}
        darwin-x86_64:
            overrides: {}
        linux-x86_64:
            overrides: {}
        windows-amd64:
            overrides: {}
