schema_version = "1.0.0"
id = "copy_render_settings"
name = "Copy Render Settings"
version = "2.0.0"
tagline = "Allows to copy a selection of render settings from current  . . "
maintainer = "Community"
type = "add-on"
tags = ["Render"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/render_copy_settings"
copyright = ["2024 Bastien Montagne"]
