schema_version = "1.0.0"
id = "collection_manager"
name = "Collection Manager"
version = "2.24.12"
tagline = "Manage collections and their objects"
maintainer = "Ryan Inch"
type = "add-on"
tags = ["User Interface"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://extensions.blender.org/add-ons/collection-manager/"
copyright = ["2024 Ryan Inch"]
