schema_version = "1.0.0"
id = "snap_utilities_line"
name = "Snap Line Tool"
version = "6.8.1"
tagline = "Extends Blender Snap controls"
maintainer = "Germano Cavalcante (mano-wii)"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://projects.blender.org/extensions/mesh_snap_utilities_line"
copyright = ["2024 Germano Cavalcante"]
