schema_version = "1.0.0"
id = "boltfactory"
name = "BoltFactory"
version = "0.4.2"
tagline = "Add a bolt or nut"
maintainer = "Community"
type = "add-on"
tags = ["Add Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/add_mesh_BoltFactory"
copyright = ["2024 Aaron Keith"]
