schema_version = "1.0.0"
id = "refine_tracking_solution"
name = "Refine tracking solution"
version = "1.1.5"
tagline = "Refine motion solution by setting track weight according to . . "
maintainer = "Community"
type = "add-on"
tags = ["Tracking"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/space_clip_editor_refine_solution"
copyright = ["2024 Stephen Leger"]
