schema_version = "1.0.0"
id = "coat_applink"
name = "3D-Coat Applink"
version = "4.9.37"
tagline = "Transfer data between 3D-Coat/Blender"
maintainer = "Community"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/io_coat3D"
copyright = ["2024 Kalle-Samuli Riihikoski (haikalle)"]
[permissions]
files = "Requires access to 3D Coat and its directory"
