schema_version = "1.0.0"
id = "modifier_tools"
name = "Modifier Tools"
version = "0.2.6"
tagline = "Modifiers Specials Show/Hide/Apply Selected"
maintainer = "Community"
type = "add-on"
tags = ["User Interface"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/space_view3d_modifier_tools"
copyright = ["2024 Meta Androcto", "2024 saidenka"]
