schema_version = "1.0.0"
id = "geodesic_domes"
name = "Geodesic Domes"
version = "0.3.6"
tagline = "Create geodesic dome type objects"
maintainer = "Community"
type = "add-on"
tags = ["Add Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/add_mesh_geodesic_domes"
copyright = ["2024 Andy Houston"]
