schema_version = "1.0.0"
id = "magic_uv"
name = "Magic UV"
version = "6.7.1"
tagline = "UV Toolset. See Add-ons Preferences for details"
maintainer = "Community"
type = "add-on"
tags = ["UV"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/magic_uv"
copyright = [
    "2024 Nutti",
    "2024 Mifth",
    "2024 Jace Priester",
    "2024 kgeogeo",
    "2024 mem",
    "2024 imdjs",
    "2024 Keith (Wahooney) Boshoff",
    "2024 McBuff",
    "2024 MaxRobinot",
    "2024 Alexander Milovsky",
    "2024 Dusan Stevanovic",
    "2024 MatthiasThDs",
    "2024 theCryingMan",
    "2024 PratikBorhade302",
]
