schema_version = "1.0.0"

id = "animall"
version = "0.14.0"
name = "AnimAll"
tagline = "Animate mesh, lattice, curve and surface data"
maintainer = "Damien Picard <dam.pic@free.fr>"
type = "add-on"
website = "https://projects.blender.org/extensions/animation_animall"
tags = ["Animation"]

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later",]
copyright = [
  "2011-2014 Daniel Salazar",
  "2019-2026 Damien Picard",
]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  "docs/",
  "pyproject.toml",
  ".*",
  "*.blend",
  "*.blend[0123456789]",
  "*.md",
  "*.po",
  "*.pot",
  "*.sh",
  "*.zip",
]
