name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure
      run: |
        sudo apt update
        sudo apt install build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libglew-dev
    - name: make
      run: |
        mkdir ~/bforartistsrepo
        cd ~/bforartistsrepo
        git clone https://github.com/Bforartists/Bforartists
        mkdir ~/bforartistsrepo/lib
        cd ~/bforartistsrepo/lib
        svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64
        cd ~/bforartistsrepo/Bforartists
        make

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: ${{ env._MAIN_DIR }}/bforartistsrepo/build_linux/bin/

