name: build_linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make libs dir
      run: ~/home/runner/work/Bforartists/lib
    - name: change dir to lib
      run: cd ~/home/runner/work/Bforartists/lib
    - name: checkout
      run: svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

    - name: change dir to make
      run: cd ~/home/runner/work/Bforartists/Bforartists
    - name: make update
      run: make udpate
    - name: make
      run: make

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: ${{ env._MAIN_DIR }}/build_linux/bin/