name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: add repo
      run: mkdir ~/bforartists
      run: cd ~/bforartists
      run: git clone https://github.com/Bforartists/Bforartists

    - name: configure libs
      run: mkdir ~/bforartists/lib
      run: cd ~/bforartists/lib
      run: svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

    - name: make
      run: cd ~/bforartists/bforartists
      run: make udpate
      run: make

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: ${{ env._MAIN_DIR }}/build_linux/bin/
