name: Mac

on:
  #push:
    #branches: [ master ]
  schedule:
    - cron: 0 0 * * 1
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: {}
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: make
      run: |
        brew install cmake git git-lfs svn
        mkdir ~/bforartistsrepo
        cd ~/bforartistsrepo
        git clone https://github.com/Bforartists/Bforartists
        cd ~/bforartistsrepo/Bforartists
        make update
        make release

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: /Users/runner/bforartistsrepo/build_darwin_release/bin/

