name: BFA CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Deps
      run: |
        apt install clang-6.0 clang-format-6.0 -y;
        ./build_files/build_environment/install_deps.sh --skip-osl --no-confirm
    - name: Configure
      run: make lite
    - name: Pack
      run: cpack
