name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: current directory
        run: pwd
      - name: make libs dir
        run: mkdir ~/libs
      - name: current directory
        run: pwd


