name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: make libs dir
        run: |
           mkdir /home/runner/work/Bforartists/libs
           cd /home/runner/work/Bforartists/libs
           pwd


